### ISSUE TITLE
ScriptProcessorNode will be deprecated in future

### ISSUE THREAD

**Issue by bogatisuman** [congrea/virtualclass#1]
According to below article, ScriptProcessorNode will be replaced by Audio Worker in future, We will have to use latest one.

https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode.

Example of audio worker
http://webaudio.github.io/web-audio-api/#audio-worker-examples

**Comment by jgupta** [comment]
We may shift to following.
http://mohayonao.github.io/audio-worker-shim/

Advantages.
It will provide fallback in case Web Worker is not present.
It will use Native Audio Worker if available.

We won't have to change code at later stage
.
Note : Not tried or researched in detail.

**Comment by jgupta** [comment]
AudioWorklet implemented.
