### ISSUE TITLE
Recording: Recorded session doesn't redirect back to recording after refresh

### ISSUE THREAD

**Issue by Sachi01** [congrea/virtualclass#1002]
In recorded session; After refreshing the session through URL(i.e. by selecting the url and pressing enter) It doesn't redirect back to the recording, instead it creates a new session (live.congrea.net).

**Comment by bogatisuman** [comment]
Fix issue 
https://github.com/vidyamantra/l.vidya.io/commit/f267a3a64055f75dc41b6c74a7eab18a23b6c458
https://github.com/vidyamantra/l.vidya.io/commit/eb76ea187b45a5ae71e4c1e7c8119d022276d72d
https://github.com/vidyamantra/l.vidya.io/commit/a2e96a986c9df258edf0bdb6420db5f0ce82cd7c
