### ISSUE TITLE
Poll heading should be displayed in middle.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1005]
Student side, the **Poll** heading should be displayed in middle like other apps:

![Screenshot from 2019-05-13 14-51-04](https://user-images.githubusercontent.com/36185596/57610496-8e9d7380-758e-11e9-8428-e6a6fcc13873.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by Rohitsharma2019** [comment]
fa10e3c520106aafa5676da425283936b1f34ee7
