### ISSUE TITLE
Quiz: After refresh the question overview tab displayed.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1006]
If teacher is present on grade report tab & refresh the page, after refresh the question overview tab displayed:

**Before refresh:**
![Screenshot from 2019-05-13 15-10-30](https://user-images.githubusercontent.com/36185596/57611810-45025800-7591-11e9-8ce5-84cbf934e834.png)

**After refresh:**
![Screenshot from 2019-05-13 15-10-54](https://user-images.githubusercontent.com/36185596/57611834-53507400-7591-11e9-9f57-5c4974d61b1f.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
![grade report tab on quiz](https://user-images.githubusercontent.com/38027574/62916641-dd89bd80-bdb6-11e9-9c8f-2b44d943b055.PNG)

**Comment by bogatisuman** [comment]
Not a bug.
