### ISSUE TITLE
Recording: Horizontal scroll hidden behind the seek bar.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1007]
Horizontal scroll hidden behind the seek bar.

![Screenshot from 2019-05-13 15-24-37](https://user-images.githubusercontent.com/36185596/57612869-3fa60d00-7593-11e9-9592-f50a16f71fcb.png)

The scroll width should be increased also:
![Screenshot from 2019-05-13 15-26-14](https://user-images.githubusercontent.com/36185596/57612980-767c2300-7593-11e9-9407-950d8d1a65cb.png)

**Comment by uditbh** [comment]
fixed

**Comment by meevm** [comment]
The scroll bar is not easily accessible yet. It should be more wide. 
![Screenshot from 2019-06-27 11-44-17](https://user-images.githubusercontent.com/12167050/60241886-f5be7f80-98d1-11e9-8f55-575048dcdd77.png)

**Comment by Sudhanshu0044** [comment]
To be effective it should be more wide.

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
Fix at https://github.com/bogatisuman/virtualclass/commit/5a622f7c85286e235970dfdb8133e0272324797f
