### ISSUE TITLE
When the video processing after upload, the play button click and tooltip must be disabled.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1011]
When uploaded video is under processing, the click must be disabled for the play button & tooltip must not be displayed:

![Screenshot from 2019-05-13 16-14-37](https://user-images.githubusercontent.com/36185596/57615818-3a988c00-759a-11e9-9c97-31672bf81e09.png)

**Comment by uditbh** [comment]
could not reproduce, during uploading it never goes in the processing phase. Video is uploading in milliseconds even it has 3 hours duration.

**Comment by ypshukla** [comment]
I have uploaded a 306 MB video file, which takes approx 7-8 minutes in processing. During the processing, if hover on play button, the pointer cursor and tooltip displayed.
![Screenshot from 2019-07-08 10-19-36](https://user-images.githubusercontent.com/36185596/60784064-08a34080-a16b-11e9-9cbb-f9aa8f73d20a.png)

**Comment by ypshukla** [comment]
reproducing

**Comment by Shubhamvaishala** [comment]
https://github.com/Shubhamvaishala/virtualclass/commit/1d20d5543f62eda9fdb2b238f3987e85afeea5dc
