### ISSUE TITLE
The question format should be same for everywhere in Poll.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1015]
**When teacher publish the poll, the question looks like below to both teacher & student:**
![Screenshot from 2019-07-08 12-39-53](https://user-images.githubusercontent.com/36185596/60791211-c2f17280-a180-11e9-99e1-c6cee91c8c7f.png)

**But after switch to other apps & back to poll, student clicks on Poll result, the question looks like below:**
![Screenshot from 2019-07-08 12-40-13](https://user-images.githubusercontent.com/36185596/60791242-d13f8e80-a180-11e9-8a30-43aa29556300.png)

- The formatting should be remain same.

**Comment by ypshukla** [comment]
reproducing

**Comment by Shubhamvaishala** [comment]
Not reproduced
