### ISSUE TITLE
Poll result changed after refresh.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1016]
After attempting the poll, when result displayed to student, it looks like:
![Screenshot from 2019-07-08 10-36-42](https://user-images.githubusercontent.com/36185596/60784405-70a65680-a16c-11e9-9166-3d1510394f9d.png)

But after refresh, the heading changed from **Poll** to **Poll result:**
![Screenshot from 2019-07-08 10-37-00](https://user-images.githubusercontent.com/36185596/60784408-7439dd80-a16c-11e9-95d6-9f5277fb3765.png)

![Screenshot from 2019-07-08 10-37-15](https://user-images.githubusercontent.com/36185596/60784413-7865fb00-a16c-11e9-98a7-712ec02643f4.png)

**Comment by Sudhanshu0044** [comment]
This issue is also being reproduced before attempting the poll

**Comment by ypshukla** [comment]
not reproduced
