### ISSUE TITLE
Precheck button not working properly on click.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1017]
When click on **"Start"** button string for precheck, it works properly.
But clicking anywhere outside of string, precheck doesn't run.

![Screenshot from 2019-05-14 18-02-34](https://user-images.githubusercontent.com/36185596/57698123-77d04d00-7672-11e9-8484-281d8a06fe69.png)

**Comment by Sudhanshu0044** [comment]
Not reproduced
