### ISSUE TITLE
Screen share request on mobile

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1018]
Student is not receiving request on mobile to sharing screen on mobile

**Comment by Shubhamvaishala** [comment]
In this case when student go to his mobile browser's setting and enable desktop site option after that he will receive request screen share but on mobile we can't add any extension on browser. now we will remove screen share icon from that particular student at teacher side user list.

**Comment by ypshukla** [comment]
The screenshare button should be removed for the student, who logged in from mobile.

**Comment by bogatisuman** [comment]
Improve with notification at https://github.com/bogatisuman/virtualclass/commit/640ce0bfa5a575921a9013f4bd5268997e6ccfc8,

If user joins in mobile as desktop then it's fine to not supporting screen sharing on mobile.
