### ISSUE TITLE
Hand raise icon not showing at teacher's end

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1024]
If the teacher(in chrome) has refreshed his screen and during that time a student from Firefox raises hand then it doesn't show on teacher's end.
![screenshot-lh3 googleusercontent com-2019 05 22-11-59-25](https://user-images.githubusercontent.com/12167050/58152037-19662880-7c89-11e9-8aea-4a82d163ac3c.png)

**Comment by meevm** [comment]
Issue still exist in both chrome and firefox. When teacher refreshes the screen, the raise hand by student does not reflect on his screen.

**Comment by Sudhanshu0044** [comment]
After refresh hand raise number increased

![Screenshot from 2019-07-11 14-01-53](https://user-images.githubusercontent.com/38027574/61035283-80c86b00-a3e4-11e9-879b-b228a42841c4.png)

**Comment by ypshukla** [comment]
Also produced on chrome.
If teacher's window is getting refreshed, at the same time if student raise hand. The count doesn't display at teacher's window.

After that if student select/unselect raise hand, no response received to teacher.
![Screenshot from 2019-08-13 12-13-20](https://user-images.githubusercontent.com/36185596/62920556-c2717a80-bdc3-11e9-9c67-251f041abc2c.png)
