### ISSUE TITLE
During document sharing, the page is not scrolling when teacher does any annotation

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1028]
If the teacher is doing any annotation at the bottom of the page. The page is not scrolling automatically at students's end. 
![screenshot-lh3 googleusercontent com-2019 05 22-11-55-41](https://user-images.githubusercontent.com/12167050/58151873-a9f03900-7c88-11e9-8bdc-25c63dfb7f13.png)

**Comment by ypshukla** [comment]
reproduced
