### ISSUE TITLE
Issue with the quiz timer

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1030]
1. Before the quiz is published the elapsed timer starts running and creates confusion. It should not start unless until the quiz is published
![2](https://user-images.githubusercontent.com/38027574/58399768-dfc16300-8076-11e9-9ca2-b440eac9711a.png)
2. There is timer difference of **3secs** from student and teacher in quiz. Reason is that after refreshing the Congrea while publishing quiz the timer starts from 4 sec in teacher and starts from 0 in student side
![Screenshot from 2019-05-27 11-57-38](https://user-images.githubusercontent.com/38027574/58399852-2616c200-8077-11e9-8763-50b0487437aa.png)

3. After the quiz is published the teacher refreshes the quiz and starts the quiz again the timer stets again from same point where the quiz was refreshed
![Screenshot from 2019-05-28 14-13-21](https://user-images.githubusercontent.com/38027574/58466630-a4e32c00-8157-11e9-8a3a-b68932547f78.png)

**Comment by ypshukla** [comment]
reproduced.

**Comment by bogatisuman** [comment]
This bug is not any more in new code.
