### ISSUE TITLE
Quiz gets disappear after refresh at teacher's end

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1032]
Steps:
1. Teacher publishes a quiz
2. After few seconds refresh the Congrea tab
3. After refreshing the quiz popup gets disappear
![Screenshot from 2019-05-28 14-09-28](https://user-images.githubusercontent.com/38027574/58464531-7b280600-8153-11e9-8143-f4013860a908.png)

**Comment by Shubhamvaishala** [comment]
reproduce after refresh

**Comment by ypshukla** [comment]
Duplicate #1050 
Not reproduced.
