### ISSUE TITLE
Quiz gets disappear after refreshing the congrea tab at student's end

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1033]
Steps:
1. After the quiz published refresh the Congrea tab at student's side
2. After refreshing the quiz gets disappear form the student's side
![Screenshot from 2019-05-28 14-07-35](https://user-images.githubusercontent.com/38027574/58464986-5b451200-8154-11e9-8b70-8086049e9f46.png)

Console error
![Screenshot from 2019-05-28 14-08-05](https://user-images.githubusercontent.com/38027574/58465075-92b3be80-8154-11e9-8a0a-f2e3bedbf7e6.png)

**Comment by Shubhamvaishala** [comment]
reproduce on student side after refresh

**Comment by Shubhamvaishala** [comment]
not reproduce
