### ISSUE TITLE
New student didn't get quiz

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1034]
Steps:
Once the quiz is published a new student joins the session and the student screen will be completely blank even after refreshing the Congrea tab multiple time.
![Screenshot from 2019-05-28 14-06-21](https://user-images.githubusercontent.com/38027574/58465387-37360080-8155-11e9-8dd2-5773935a22b2.png)

**Comment by Shubhamvaishala** [comment]
not reproduce
