### ISSUE TITLE
Refresh issue with poll

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1035]
Steps:
1. If teacher publish a poll and refreshes the Congrea tab at that time the poll gets disappear from the students window
![Screenshot from 2019-05-28 15-14-23](https://user-images.githubusercontent.com/38027574/58468515-4f108300-815b-11e9-9adc-1ba7f1d5c86b.png)

**Comment by Shubhamvaishala** [comment]
reproduced with same steps

**Comment by ypshukla** [comment]
Duplicate #1049 
Reproducing in different way. Created a new issue for that.
