### ISSUE TITLE
Issue in screen share

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1036]
When teacher request student to share screen and on student side desktop plugin is not installed on chrome then student gets pop up when teacher shares screen
Steps to reproduce (Desktop plugin should not be installed on student browser)
1. request screen share to student
2. student receives popup to install the plugin desktop plugin but student closes the popup and not install this plugin
3. Then teacher starts sharing screen then the student receives popup instead of shared screen
4. Student closes the popup again then also the shared screen not appears at student 's Congrea tab

**Comment by Shubhamvaishala** [comment]
reproduce with same steps

**Comment by ypshukla** [comment]
Duplicate #1056
