### ISSUE TITLE
Issue with student side user list and common chat

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1037]
Steps to reproduce:
1. When teacher joins the session and turn the camera the **on**
2. Now teacher clears the history of the browser or change the browser the join the session again
3. When teacher joins the session, the user list on students's window get refresh and "search user" and common chat user field shifts up. At that time teacher side camera is turned off
![Screenshot from 2019-06-05 10-44-26](https://user-images.githubusercontent.com/38027574/58932206-674a5880-8780-11e9-9eb7-8d73aaf530b7.png)

Once the Shubham code is finalised by the Suman Sir then these correction would be done

**Comment by Shubhamvaishala** [comment]
Not reproduced because this bug is fixed few day ago
