### ISSUE TITLE
Recording: Seek bar moving with mouse cursor.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1046]
During the recording play, if user seek to forward; after 2-3 clicks the seek bar starts moving with mouse cursor. 

Only restarting the page resolves this issue.

**Comment by meevm** [comment]
The error did not reproduce

**Comment by Sachi01** [comment]
This is a random issue and is still occurs at times

**Comment by ypshukla** [comment]
Didn't reproduced.

**Comment by ypshukla** [comment]
Issue occurs randomly.

**Comment by bogatisuman** [comment]
This issue is very rare not random, closing the issue now.
