### ISSUE TITLE
Quiz & Poll not working on KTS

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1051]
Quiz & Poll are not working on KTS Moodle sites.

**Comment by bogatisuman** [comment]
Fixed https://github.com/congrea/virtualclass/commit/d52461eea8f90013b569933b00942bfbbd45eb4d

**Comment by ypshukla** [comment]
Not resolved yet.

**Comment by Sudhanshu0044** [comment]
Not got any issue
