### ISSUE TITLE
Issue with Firefox browser

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1052]
If teacher join the session from Firefox browser and enables the webcam and refresh the window multiple times after that on teacher's screen Congrea disconnecting and connecting every moment
![Capture](https://user-images.githubusercontent.com/38027574/59341463-810e1180-8d25-11e9-8f24-7887eb29960e.PNG)
On user list a duplicate user is created on the name of teacher

**Comment by bogatisuman** [comment]
It's not reproducing, Re-open in case re-producing, Please provide the detail steps.
