### ISSUE TITLE
issue with the recording

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1054]
While playing recording a blank space comes after seeking the recording while playing
![Screenshot from 2019-06-12 11-46-26](https://user-images.githubusercontent.com/38027574/59342295-237ac480-8d27-11e9-8331-1fb4329b002e.png)

**Comment by bogatisuman** [comment]
Fixed at https://github.com/congrea/virtualclass/commit/5d4f22635253afb135442935de36e39183893a05
