### ISSUE TITLE
Issue with document sharing

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1055]
If teacher uploads a fresh document on Congrea and share it, the document appears on the teacher's and student's screen is zoomed-in automatically instead of fit to screen.
![Screenshot from 2019-06-12 11-33-13](https://user-images.githubusercontent.com/38027574/59342446-70f73180-8d27-11e9-823f-431f35126da7.png)
Two students received same document page in two different ways:
1. One is zoomed in
2. Another is fit to screen
![Screenshot from 2019-06-12 11-32-54](https://user-images.githubusercontent.com/38027574/59342754-fed31c80-8d27-11e9-8f9f-2ee1a921b598.png)

**Comment by ypshukla** [comment]
Reproducing with same steps.
