### ISSUE TITLE
Issue with the screen share

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1056]
If teacher request a student to share screen don't having desktop selector plugin and student closes the popup and not install the plugin the student will receive popup when teacher shares the screen.
![Screenshot from 2019-06-12 11-25-51](https://user-images.githubusercontent.com/38027574/59342710-e82cc580-8d27-11e9-9c97-478f4b693122.png)

**Comment by Shubhamvaishala** [comment]
reproduced -  If teacher request a student to share screen don't having desktop selector plugin and student closes the popup and not install the plugin the student will receive popup when teacher shares the screen.

**Comment by ypshukla** [comment]
Reproduced with same steps.
