### ISSUE TITLE
Issue with the common chat

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1057]
If a user sends chat on common chat room the another users receives chat BUT without opening the chat room the chat is appeared on the screen. It's seems that it's overlapping the user list because in the bottom a user field is appearing with text "Search user"
The same issue is reported in recording also
![Screenshot from 2019-06-12 12-40-31](https://user-images.githubusercontent.com/38027574/59343065-aa7c6c80-8d28-11e9-94f3-6205db5ad4b2.png)

**Comment by uditbhargava** [comment]
Couldn't reproduce

**Comment by Sudhanshu0044** [comment]
Still being reproduce on Moodle hub
![Screenshot from 2019-06-24 17-09-35](https://user-images.githubusercontent.com/38027574/60016123-e0afd980-96a2-11e9-8505-ddd3ad14ee12.png)

**Comment by Shubhamvaishala** [comment]
https://github.com/Shubhamvaishala/virtualclass/commit/7bc615e1eafce938009baf7cf2274264fc907437
bug fix
