### ISSUE TITLE
Issue with poll

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1058]
In poll the count of no. of users is not appearing correct. The count should equal to the no. of students present in the real time.
For suggestion, it's not necessary to collect vote from the teacher.
![Screenshot from 2019-06-11 11-33-30](https://user-images.githubusercontent.com/38027574/59343251-1232b780-8d29-11e9-9f78-eb2d564804f8.png)

**Comment by Shubhamvaishala** [comment]
random bug

**Comment by Sachi01** [comment]
Reproduced

![132](https://user-images.githubusercontent.com/50192706/62919430-46c1fe80-bdc0-11e9-9c46-d9058cbc955f.png)
