### ISSUE TITLE
Stop sharing button hidden behind Recording button.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1066]
After requesting the screenshare with student, teacher getting the stop sharing button hidden behind the Recording button.
![Screenshot from 2019-06-15 16-52-52](https://user-images.githubusercontent.com/36185596/59550866-0b58ae80-8f8e-11e9-9e1e-45e9d96482a1.png)

**Comment by bogatisuman** [comment]
Re-open in case of not fixed.
