### ISSUE TITLE
Click not working on edges of Precheck button.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1067]
If click on the middle of Precheck button, it works properly.
But at the edges of Precheck button, click is not working.

![Screenshot from 2019-06-15 17-20-00](https://user-images.githubusercontent.com/36185596/59551101-0d247100-8f92-11e9-8575-1b1c46fbb4fb.png)

**Comment by uditbhargava** [comment]
fixed #b9fa2ea
