### ISSUE TITLE
Whiteboard: Active all button resize and drag shapes not working

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1077]
While selecting the active all button, teacher is unable to drag or resize the drawn shapes .
![Capture](https://user-images.githubusercontent.com/36185596/59666310-36334480-91d2-11e9-9d32-98f20c6025c5.PNG)

Console error:
![Capture2](https://user-images.githubusercontent.com/36185596/59666399-64b11f80-91d2-11e9-8cce-2780e577e696.PNG)

**Comment by Sudhanshu0044** [comment]
Not reproduced
