### ISSUE TITLE
Screenshare: Teacher is able to request screenshare with multiple students.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1088]
Teacher is able to request screenshare with multiple students at the same time.

When teacher click on request screenshare button for one student, it must be disable for remaining students until the response received from requested student.

If student didn't respond, teacher must be able to reject the screen share request by clicking on same button. After that all request screenshare buttons should be enabled.

**Comment by Sachi01** [comment]
Reproduced

**Comment by bogatisuman** [comment]
On new request of screen share, previous one would be cancelled. So there is always only one active screen share request.
