### ISSUE TITLE
Document sharing: Automatically redirected to first page.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1089]
During the document sharing, if teacher is present on somewhere in the mid of document (suppose on 3rd page) & at the same time teacher has uploaded the document which is processing in the background.

When the document processing completed in background, teacher automatically redirects to 1st page of document.

**Comment by Sachi01** [comment]
Could not be reproduced
Fixed.

**Comment by ypshukla** [comment]
Still reproduced with same steps
