### ISSUE TITLE
Screen share buttons UI affected.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1097]
**Stop sharing** and **Share to all /Self view** buttons UI affected (produced on firefox):

![Capture3](https://user-images.githubusercontent.com/36185596/59903541-e39a9800-941e-11e9-9c1c-9dece72def0d.PNG)
![Capture4](https://user-images.githubusercontent.com/36185596/59903543-e4332e80-941e-11e9-94ce-52417c2f3279.PNG)

**Comment by uditbhargava** [comment]
fixed

**Comment by bogatisuman** [comment]
Re-open in case of it's not fixing.
