### ISSUE TITLE
UI affected while opening multiple Private chat windows.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1098]
If teacher/user opens multiple private chat windows. It shifts down and UI misaligned:
![Capture7](https://user-images.githubusercontent.com/36185596/59904710-e0ed7200-9421-11e9-8b91-c096fcce35a8.PNG)

![Capture8](https://user-images.githubusercontent.com/36185596/59904860-3de92800-9422-11e9-840a-deafd0d894f5.PNG)

**Comment by Sachi01** [comment]
reproduced
