### ISSUE TITLE
The error message displayed in multiple lines.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1101]
The error message displayed in 3 lines when window size 1024x768:
![Screenshot from 2019-06-21 15-00-55](https://user-images.githubusercontent.com/36185596/59913354-a097ef00-9435-11e9-9600-f10ae42f98f4.png)

The same error message displayed in 4 lines when windows size larger than 1024x768:
![Screenshot from 2019-06-21 15-01-06](https://user-images.githubusercontent.com/36185596/59913428-befdea80-9435-11e9-8b8b-b328105917f5.png)

**Comment by Rohitsharma2019** [comment]
fixed
