### ISSUE TITLE
Full screen button should be removed from video sharing player.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1104]
During the video sharing, if teacher use the Congrea Full screen button & then also use the video player Full screen button and then press ESC to exit. Now the Congrea Full screen button is not functional. It looks like below:
![Screenshot from 2019-06-21 17-00-43](https://user-images.githubusercontent.com/36185596/59919829-21f77d80-9446-11e9-8912-d64ec914c90d.png)

**Comment by Sachi01** [comment]
Fixed and buttons are working as per their meaning.

**Comment by ypshukla** [comment]
still reproduced with same steps
