### ISSUE TITLE
Orientation of Some slides are changed (turning upside down) in document sharing

### ISSUE THREAD

**Issue by Sachi01** [congrea/virtualclass#1112]
Orientation of slides are inverted randomly during document sharing. Its a long time pending issue with no specific steps.

Affected User: Sometimes presenter, sometimes student and at times both

**Comment by Sachi01** [comment]
Reproduced randomly

**Comment by bogatisuman** [comment]
Fix at 
https://github.com/bogatisuman/virtualclass/commit/07520c32229ea96388ec7292832faf681f1ea787
https://github.com/bogatisuman/virtualclass/commit/14c7445a5362ee6bbda14d98aa29e3da51b1e942
