### ISSUE TITLE
Issue with video

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1114]
Steps:
1. Fist join the students in the session(Audio/Video- OFF)
2.  Make changes in the video setting from congrea setting page on Moodle(Audio/Video- ON)
3. Join the teacher

Results:
![Screenshot from 2019-06-25 16-08-36](https://user-images.githubusercontent.com/38027574/60092104-c853c380-9763-11e9-8141-f62501d71f4c.png)

**Comment by Shubhamvaishala** [comment]
Not reproduced
