### ISSUE TITLE
Issue with screen share request

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1115]
Steps:
1. Request a student to share the screen
2. Student clicks on "NO"
Result: No change in color of request screen share button
![Screenshot from 2019-06-25 16-04-37](https://user-images.githubusercontent.com/38027574/60092292-4a43ec80-9764-11e9-88ac-ae026c5d88bd.png)

**Comment by Rohitsharma2019** [comment]
fixed
