### ISSUE TITLE
After refresh hand raise gets disable on student side

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1118]
Steps:
1. Click on hand raise on student side
2. Refresh the Congrea tab
Result: Hand raise will get hands down
![Screenshot from 2019-06-25 16-34-21](https://user-images.githubusercontent.com/38027574/60093663-a8260380-9767-11e9-851a-a09bd4f63b10.png)

**Comment by Shubhamvaishala** [comment]
reproduced after refresh

**Comment by Sachi01** [comment]
Reproduced

**Comment by bogatisuman** [comment]
Duplicate of https://github.com/congrea/virtualclass/issues/1162
