### ISSUE TITLE
Presenter video space appearing in recording, even when he did not connect camera during live session

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1121]
Presenter video space appearing in recording, even when he did not connect camera during the live session.
Random error.
![Screenshot from 2019-06-25 16-59-42](https://user-images.githubusercontent.com/12167050/60094842-c0e3e880-976a-11e9-98d4-12040ddc541b.png)
![Screenshot from 2019-06-25 16-57-22](https://user-images.githubusercontent.com/12167050/60094845-c3ded900-976a-11e9-9eae-6d1696cc0613.png)

**Comment by Sachi01** [comment]
reproduced

**Comment by bogatisuman** [comment]
This does not exist in new code.
