### ISSUE TITLE
Settings description shall be changed under 'Bulk user actions' menu on presenter screen

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1122]
Settings description shall be changed under 'Bulk user actions' menu(
![screenshot-live congrea net-2019 06 25-17-19-56](https://user-images.githubusercontent.com/12167050/60096019-9182ab00-976d-11e9-8142-8f48d26f77e2.png)
on right panel) on presenter screen. The changes shall be as follows:

1. Mute all audio -> All audio
2. Disable all video -> All video
3. Disable private chat -> Private chat
4. Disable common chat -> Common chat

**Comment by Sachi01** [comment]
Fixed.
