### ISSUE TITLE
Issue in whiteboard on Firefox browser

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1123]
Steps:
1. Join the session
2. Create page:2 on Whiteboard
3. Go to Page 1 and then go to page 2

The issue is only reproduced on firefox
Result: Navigation would be **0 of page 2**
![Screenshot from 2019-06-25 17-32-55](https://user-images.githubusercontent.com/38027574/60096918-df98ae00-976f-11e9-9be1-355c264a9b74.png)

**Comment by Shubhamvaishala** [comment]
1. On whiteboard create page 1,2. 
2. Now go to page 1 after that page 2. 
3. navigation not display pagination in proper manner.

**Comment by Sachi01** [comment]
Fixed
The issue could not be reproduced and pagination is working fine.
