### ISSUE TITLE
Issue with screenhare

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1129]
Steps:
1. Upload document on the Congrea(Teacher on firefox)
2. Share document
3. Start sharing screen
4. During the screen share join a student from Chrome
Result: Student will not get the shared screen and will get dialog box
![Screenshot from 2019-06-26 11-21-47](https://user-images.githubusercontent.com/38027574/60154683-b32f7100-9805-11e9-85ec-d8acef061755.png)

**Comment by Shubhamvaishala** [comment]
Not reproduced
