### ISSUE TITLE
Problem with chat sinking

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1131]
The personal chat between students did not sink properly. Few of the messages sent by one student did not appear on other student's screen. 
![Screenshot from 2019-06-26 12-18-09](https://user-images.githubusercontent.com/12167050/60158029-c0e8f480-980d-11e9-974b-06bcab60ce3e.png)

**Comment by meevm** [comment]
Still happens when one of the student refreshes his screen while the other one is texting him.

**Comment by Sachi01** [comment]
previous chat disappears when user refreshes congrea screen.

**Comment by bogatisuman** [comment]
Chat problem is not reproducing, missing of chat on page refresh will be fixed in future, and that issue is live on https://github.com/congrea/virtualclass/issues/1202
