### ISSUE TITLE
Request screen share: Notification to presenter

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1138]
1. When presenter request screen share from a student, the icon colour shall change at teacher's end informing him that the request has been sent to the student.
2. The icon colour was showing green even after the student had stopped sharing his screen.

![Screenshot from 2019-06-27 11-36-22](https://user-images.githubusercontent.com/12167050/60242442-539f9700-98d3-11e9-9d77-49e75a078ad4.png)

**Comment by meevm** [comment]
When presenter request screen share from a student, the icon colour shall change at teacher's end informing him that the request has been sent to the student.Although the student hasn't yet selected yes or no.

**Comment by Sachi01** [comment]
Reproduced

**Comment by Shubhamvaishala** [comment]
Student accept and cancel screen share request. action reflect on teacher side request screen share button color change. red color cancel request screen share and green accept screen share.
