### ISSUE TITLE
Problem in selecting document in document dashboard: Different pages showing at student and teacher's screen 

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1142]
The teacher uploaded two documents in the doc dashboard and clicked the finish button. The last page in dashboard list was visible to all the students. Nothing was visible on teacher's screen at first but after a while the first page appeared  on teacher's screen.

![Screenshot from 2019-06-28 10-51-22](https://user-images.githubusercontent.com/12167050/60322231-8feafa00-999c-11e9-9e43-6b1405d3d63d.png)

![Screenshot from 2019-06-28 10-50-34](https://user-images.githubusercontent.com/12167050/60322333-cf194b00-999c-11e9-9820-9e6c306797dc.png)

**Comment by Sudhanshu0044** [comment]
After uploading the new document the first page starts sharing.
While sharing if student refreshes the Congrea and teacher continuously changes the page the wrong page is displayed at student's tab
![Screenshot from 2019-07-11 16-21-35](https://user-images.githubusercontent.com/38027574/61045295-35b85300-a3f8-11e9-8bdd-f4e828ac8a3b.png)

**Comment by Sachi01** [comment]
Reproduced

**Comment by bogatisuman** [comment]
This problem is not coming at new code,  Please reopen the issue with the steps in case of reproducing.
