### ISSUE TITLE
Document sharing and Screen refresh

### ISSUE THREAD

**Issue by Sachi01** [congrea/virtualclass#1143]
Presenter opens the document sharing
Refreshes the screen either with refresh icon or URL select and enter
If the document on the presenter screen is in the form of grid view
![2](https://user-images.githubusercontent.com/50192706/60330201-8c14a300-99af-11e9-9531-51bbf5b85d16.png)
 but after refresh he/she is taken to the selected page of the document rather than the grid view.
see here
![3](https://user-images.githubusercontent.com/50192706/60330224-9b93ec00-99af-11e9-9935-c3558820421d.png)

**Comment by Sachi01** [comment]
Presenter could not connect back in firefox after the refresh.

**Comment by bogatisuman** [comment]
If there is grid view with slide selected and teacher does page refresh, it's fine to not display grid view automatically on page refresh.

Presenter is connecting after page refresh on firefox version 67. Please reopen the issue, if the bug still does exist on firefox.
