### ISSUE TITLE
Presenter whiteboard got blank, whereas there was content displayed on student's screen 

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1145]
When the presenter moved from documents sharing to whiteboard, his whiteboard got blank, whereas there was content displayed on student's screen. Random error
![Screenshot from 2019-06-28 14-33-41](https://user-images.githubusercontent.com/12167050/60331590-9e441080-99b2-11e9-8c38-870945146580.png)

**Comment by Sudhanshu0044** [comment]
Steps:
1. After refreshing the teacher and student multiple times and switching the app at moment results
missing of the annotation bar on white board and the content also get disappeared from the teacher side.
![Screenshot from 2019-07-11 11-47-41](https://user-images.githubusercontent.com/38027574/61026808-127aad00-a3d2-11e9-8874-b66c72d4ec16.png)

**Comment by Sachi01** [comment]
Reproduced

**Comment by bogatisuman** [comment]
This is not reproducing.
