### ISSUE TITLE
Display error in chatroom when common chat is disabled by teacher 

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1146]
The user list overlaps the chatroom at student's end when the teacher disabled common chat from bulk user action.
![Screenshot from 2019-06-28 16-09-39](https://user-images.githubusercontent.com/12167050/60337172-ecabdc00-99bf-11e9-8bc7-bc87c5334692.png)
![Screenshot from 2019-06-28 16-10-42](https://user-images.githubusercontent.com/12167050/60337174-ef0e3600-99bf-11e9-9c67-ad40aaf5de2a.png)

**Comment by Shubhamvaishala** [comment]
not reproduce
