### ISSUE TITLE
Teacher's audio is mute but its showing green to few students 

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1147]
Teacher's audio is mute. But the audio symbol for teacher is showing green to few students.
![Screenshot from 2019-06-28 16-59-05](https://user-images.githubusercontent.com/12167050/60339440-621aab00-99c6-11e9-819b-3d76eedf00b6.png)

**Comment by Sudhanshu0044** [comment]
Steps:
1. Join the teacher in a session
2. Before the refreshing the student the symbol works perfectly
3. Once the student refresh the window the icon doesn't works.

**Comment by Sachi01** [comment]
Reproduced

**Comment by shubh007-repo** [comment]
Not Reproduced

**Comment by Shubhamvaishala** [comment]
Not Reproduced

**Comment by bogatisuman** [comment]
Closing the issue as it's not reproducing in new code.
