### ISSUE TITLE
Congrea not opening in windows [Microsoft edgeHTML 17.17134]

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1148]
Congrea did not open at student's end in windows  [Microsoft edgeHTML 17.17134]
![Screenshot (1)](https://user-images.githubusercontent.com/12167050/60502657-dcf00880-9cdb-11e9-9ec2-7cbe811fb404.png)
![Screenshot (2)](https://user-images.githubusercontent.com/12167050/60502660-df526280-9cdb-11e9-8748-de6d978a6364.png)

**Comment by Sachi01** [comment]
Reproduced

**Comment by bogatisuman** [comment]
Congrea will be supported completely from Edge 76. It will be launched soon. In case of any one wants to test, please get the beta version at [Edge 76]( https://www.microsoftedgeinsider.com/en-us/download/l)

**Comment by bogatisuman** [comment]
I am closing the issue for now.
