### ISSUE TITLE
Screenshare request for Student: Shared screen is visible to other student for few seconds even though request was not sent to him

### ISSUE THREAD

**Issue by Sachi01** [congrea/virtualclass#1150]
Screen share was visible to other student even though screen share request was not send to him.
Steps: (refer to Screenshot)
1. Teacher requests a screen share request to student1
2. Student2 accepts the request and selects the screen to be shared.
3. As soon as share button is pressed by student 2, the shared screen is also visible to student4 for few seconds, who should not see that screen as the share is not public yet.

![Screenshot (15)](https://user-images.githubusercontent.com/50192706/60508721-e16eee00-9ce8-11e9-8239-2514ba69e506.png)

**Comment by Sachi01** [comment]
Reproduced

**Comment by bogatisuman** [comment]
Exact copy of issue can be found at https://github.com/congrea/virtualclass/issues/1169
