### ISSUE TITLE
Document sharing: Teacher unable to select page through document dashboard And the page is not displaying on his screen

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1152]
Document sharing: Teacher unable to select page through document dashboard And the page selected by default is not displaying on teacher's screen.
![Screenshot from 2019-07-03 14-21-16](https://user-images.githubusercontent.com/12167050/60583919-8a7d1d80-9da9-11e9-8992-faaa8904bb22.png)

**Comment by Sachi01** [comment]
Fixed as it could not be reproduced.
