### ISSUE TITLE
User list: Only first-name in Firefox and both first and second name in Chrome 

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1153]
Under user list: Only first-name of a user is displaying in Firefox . Whereas both first name and second name in Chrome.
[Both Firefox and Chrome in Laptop]
![Screenshot (4)](https://user-images.githubusercontent.com/12167050/60584338-9b7a5e80-9daa-11e9-80bc-e18f7fb0bc83.png)
[Chrome on Desktop]
![Screenshot from 2019-07-03 15-47-32](https://user-images.githubusercontent.com/12167050/60584375-b947c380-9daa-11e9-94bb-1f662825837f.png)

**Comment by Sachi01** [comment]
in both the browsers the user list is displayed in the same format.
