### ISSUE TITLE
Chat : The private chat box at student's end does not close properly if the teacher request him to share screen while the chat box is open 

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1156]
Chat : The private chat box at student's end does not close properly if the teacher request him to share screen while the chat box is open 
![Screenshot from 2019-07-05 16-29-23](https://user-images.githubusercontent.com/12167050/60718714-11b1c900-9f43-11e9-994f-c4b9fb1487e3.png)

**Comment by Sudhanshu0044** [comment]
Hiding chat is being reproduced when student is on white board.

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by Shubhamvaishala** [comment]
This is not a bug
