### ISSUE TITLE
Recording: Video overlapped over whiteboard in recording when seek back and forth. 

### ISSUE THREAD

**Issue by Sachi01** [congrea/virtualclass#1157]
Whiteboard was visible when the video was played after the seek backward and forward was done.
![video*whiteboard](https://user-images.githubusercontent.com/50192706/60719217-951fea00-9f44-11e9-9c7d-102edb8156f8.png)
![Screenshot from 2019-07-05 16-21-50](https://user-images.githubusercontent.com/50192706/60719223-9a7d3480-9f44-11e9-8161-053b770c7120.png)

**Comment by bogatisuman** [comment]
This bug does not exist anymore in new code.
