### ISSUE TITLE
Chat: At student's end there was no box to enter text in common chat. While he could do private chat.

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1159]
Chat: At student's end there was no box to enter text in common chat. While he could do private chat.
![Screenshot from 2019-07-05 17-11-28](https://user-images.githubusercontent.com/12167050/60720460-79b6de00-9f48-11e9-9183-241e68a3c64b.png)

**Comment by Sudhanshu0044** [comment]
It seems that this a random bug and not being reproduced.
