### ISSUE TITLE
Recording: Tooltip is hiding behind progress bar.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1161]
During recording play, if hover on play/pause button, the tooltip hidden behind the progress bar.
![Screenshot from 2019-07-08 10-43-06](https://user-images.githubusercontent.com/36185596/60784660-659ff600-a16d-11e9-9189-8cab6a49cd6e.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by Shubhamvaishala** [comment]
Fix
