### ISSUE TITLE
Raise Hand disappears on Refresh 

### ISSUE THREAD

**Issue by Sachi01** [congrea/virtualclass#1162]
Raise hand not working properly (counting issue) & also raise hand disappears after student refreshes the Congrea screen.
Steps:
1. Raise hand from any student refresh the student window
2. After refresh hand raised by student disappear but on teacher screen still it shows

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
Disappearing raised hand on student page refresh is fine, but there should not be the counting issue. 
Please re-check with the counting issue, if it still exists let me know else close the issue.

**Comment by bogatisuman** [comment]
There is no counting issue on normal case. It's fine to removing earlier raised hand on student's page refresh.
