### ISSUE TITLE
Quiz: As the quiz is not timer controlled, there's no need to display "time limit"  

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1163]
Quiz: As the quiz is not timer controlled, there's no need to display "time limit"  
![Screenshot from 2019-07-08 11-36-25](https://user-images.githubusercontent.com/12167050/60786726-2d9cb100-a175-11e9-9b37-a1581768c70d.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps and it's a enhancement part
