### ISSUE TITLE
Document sharing: Make active tool not working. The toolbar was not working 

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1164]
Under document sharing 2 documents were uploaded.:
Document 1: 8 pages
Document 2: 1 page
Document 1, first page was displaying, but from document dashboard the presenter hid the document 1, so automatically Doc 2 started appearing. But the tool bar stopped working on this new page of doc 2.
![Screenshot from 2019-07-08 12-08-00](https://user-images.githubusercontent.com/12167050/60788528-920e3f00-a17a-11e9-9f26-1dbea9bcd5f1.png)
![Screenshot from 2019-07-08 12-10-06](https://user-images.githubusercontent.com/12167050/60788536-94709900-a17a-11e9-9337-9ed32853e8b1.png)

**Comment by Sudhanshu0044** [comment]
It seems this was random issue. Not reproduced
