### ISSUE TITLE
Poll: The poll closed message is same for both teacher & student for unattended poll.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1165]
If poll closing mode is by timer & no attempt received and poll timed out. The below message displayed to teacher same as student.
![Screenshot from 2019-07-08 12-42-31](https://user-images.githubusercontent.com/36185596/60790234-9d636980-a17e-11e9-9304-4c7ead857321.png)

When poll closing mode is by instructor & teacher close the poll manually, the same message appears:
![Screenshot from 2019-07-08 13-01-12](https://user-images.githubusercontent.com/36185596/60791050-786ff600-a180-11e9-829d-fbb1e94f2dc5.png)

**Comment by Sudhanshu0044** [comment]
Message should not display to student

**Comment by bogatisuman** [comment]
It's fine to display same message to teacher and student in case of not receiving of any vote in any mode.
Of course message should be displayed to student that he would know any participate did not vote for the poll.
However I remove the close button on close-message-box at https://github.com/bogatisuman/virtualclass/commit/4344270c485715ec488f130f4fda42a695202f30
