### ISSUE TITLE
Complete screen does not get faded when session closes while student in full screen mode

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1167]
Complete screen does not get faded when session closes while student in full screen mode. Chat room still comes active. And some times complete screen is active(not faded/white). 
![Screenshot from 2019-07-08 15-00-59](https://user-images.githubusercontent.com/12167050/60802326-410c4400-a196-11e9-89d5-6c01165f716d.png)

**Comment by Sudhanshu0044** [comment]
![Screenshot from 2019-07-11 12-44-46](https://user-images.githubusercontent.com/38027574/61029919-d3e8f080-a3d9-11e9-9673-d0ec5c0f853b.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
