### ISSUE TITLE
Request screen share: Blank white screen at student's end 

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1169]
1. Presenter request screen share from one of the student.
2. The student selected "Yes" option.
3. Even though the presenter does not click 'Share to all', the screen appears to rest of the students for fraction of seconds. 
4. Until the teacher does not click 'Share to all', the rest of the students get a blank white screen.

**Comment by Shubhamvaishala** [comment]
reproduced with same steps

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
The bug of  screen was appearing to rest of the students for fraction of seconds is fixed now.
