### ISSUE TITLE
Document sharing: The message "Document uploaded successfully" shall remove automatically if not closed by presenter.

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#1171]
1. The presenter uploaded a document 
2. The message comes : "Document uploaded successfully"
3. The teacher does not close(X) this message, instead go on the doc shared .
4. When he comes back to dashboard the message still displays. It shall get removed automatically.

**Comment by Sudhanshu0044** [comment]
![Screenshot from 2019-07-11 12-40-55](https://user-images.githubusercontent.com/38027574/61029676-32619f00-a3d9-11e9-8fa6-0262e0b5144e.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
The success message box will close automatically after four seconds of uploaded document.
