### ISSUE TITLE
Quiz: Tabs switching automatically on single click.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1174]
After publishing the quiz, when teacher click on **Questions overview** tab, the **Grade report** highlighted automatically.

![Screenshot from 2019-07-09 17-12-00](https://user-images.githubusercontent.com/36185596/60885680-bf87e500-a26d-11e9-8b6c-fb8f0abc4b1e.png)

**Comment by Sudhanshu0044** [comment]
Clicking on Questions overview the the selected tab automatically switches but not the content
![Screenshot from 2019-08-07 14-38-04](https://user-images.githubusercontent.com/38027574/62610271-fe6a9280-b920-11e9-97cd-0f16345412fd.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
