### ISSUE TITLE
Poll result bar graph is not coming properly

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1175]
1. Publish a quiz
2. After quiz is over check the results in bar graph
3. All the bar should display in same size
![Screenshot from 2019-08-08 10-55-27](https://user-images.githubusercontent.com/38027574/62677563-6cb85f00-b9cc-11e9-8326-8effe7b0b4ec.png)

**Comment by meevm** [comment]
Working fine now
![Screenshot from 2019-08-13 16-01-55](https://user-images.githubusercontent.com/12167050/62935099-d036f800-bde3-11e9-8abf-996a037c376c.png)

**Comment by meevm** [comment]
![Screenshot from 2019-08-13 17-04-53](https://user-images.githubusercontent.com/12167050/62938372-90284300-bdec-11e9-83df-ae5ee2acb525.png)
