### ISSUE TITLE
Issue with settings

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1178]
Disable all the recording settings
Join the teacher
Enable the recording settings
Join the student

Result: On student side recording button is appearing but according to the setting implementation recording should not be appear on student side
![Screenshot from 2019-08-09 10-48-09](https://user-images.githubusercontent.com/38027574/62755980-b91aa200-ba93-11e9-8444-1fce1ef99dad.png)

**Comment by bogatisuman** [comment]
The changes of setting between the session would not be affected unless teacher would re-join the session.
