### ISSUE TITLE
Scroll not coming on white board

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1180]
1. Draw some content on whiteboard (Teacher screen resolution: 1024x768)
2. Student will change the screen resolution led loss of content on whiteboard
3. Horizontal scroll not coming on student side to scroll
![Screenshot from 2019-08-09 14-16-09](https://user-images.githubusercontent.com/38027574/62766718-bd08ed00-bab0-11e9-9311-da0bfde6b032.png)

**Comment by meevm** [comment]
When resizing the screen to normal/bigger size this issue is coming at both teacher as well as student's side.

**Comment by suman** [comment]
Updated fabric.js.
