### ISSUE TITLE
Issue with video track

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1181]
Turn off the trim and play the recording
After that turn on the trim play the recording the video length will be complete but the video will play properly. check the below image
![Screenshot from 2019-08-09 17-14-11](https://user-images.githubusercontent.com/38027574/62776935-94412180-bac9-11e9-9ecd-305fdfb36bfd.png)

**Comment by meevm** [comment]
After turning the Trim on, the recording video plays, but it does not get complete till end. The green progress bar does not reach till end. 
![Screenshot from 2019-08-13 12-47-16](https://user-images.githubusercontent.com/12167050/62936871-81d82800-bde8-11e9-8541-879bf65627fc.png)
