### ISSUE TITLE
Teacher video is appearing white in user list

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1183]
![Screenshot from 2019-08-09 17-28-41](https://user-images.githubusercontent.com/38027574/62777809-33ffaf00-bacc-11e9-9854-16ba52dc6fda.png)

**Comment by bogatisuman** [comment]
The teacher video is displaying in normal recording playing. There will be displayed white box for few second while you seek. After few seconds of seek, there will be displayed the teacher video however.
Please make me correct if I am wrong else close the issue.
