### ISSUE TITLE
Issue with the recording setting

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1185]
Enable all the recording setting from congrea setting page
Student will join the session
Now teacher will disable the “session recording” setting from congrea setting page
Teacher will join the session
Now on the teacher side recording control buttons are not visible but on student side it is appearing
Student side screen:
![Screenshot from 2019-08-09 17-45-14](https://user-images.githubusercontent.com/38027574/62778347-ca80a000-bacd-11e9-9d14-877aa3ec35be.png)

Teacher side window
![Capture](https://user-images.githubusercontent.com/38027574/62778439-07e52d80-bace-11e9-94bd-45c077cca3fc.PNG)

**Comment by meevm** [comment]
Still appearing 
![Screenshot from 2019-08-13 11-04-30](https://user-images.githubusercontent.com/12167050/62917632-a1f0f280-bdba-11e9-8b73-9535185a9208.png)
