### ISSUE TITLE
 Timer not runs even after publishing the quiz

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1186]
Steps:
Set timer in the quiz from Moodle
Goto congrea and publish the same quiz
The timer of the quiz will not run
Refresh the congrea
Timer will start running
![Capture](https://user-images.githubusercontent.com/38027574/62846251-304a7300-bcec-11e9-9a5f-89f5a9b57331.PNG)

**Comment by bogatisuman** [comment]
Fix it at [commit.](https://github.com/bogatisuman/virtualclass/commit/0cedee8abb689b778f9e09f90e219d762786b65a)
