### ISSUE TITLE
Issue with the video sharing

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1189]
1. Upload a video on Congrea
2. Share the video
3. On student side video doesn't appear
![video sharing issue](https://user-images.githubusercontent.com/38027574/62849822-bcfe2c80-bcfe-11e9-82d1-8614ee341880.PNG)

At this moment if student refreshes the congrea tab then it would not be able to connect again in the class
![video sharing student not connecting](https://user-images.githubusercontent.com/38027574/62850368-4a8e4c00-bd00-11e9-8a2a-a12b45f2ddd4.PNG)

**Comment by bogatisuman** [comment]
Fixed at https://github.com/congrea/virtualclass/commit/621258493527acb8b600269db699a3c56c8f9882
