### ISSUE TITLE
Issue with the quiz elapsed time

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1191]
1. Publish quiz without timer
2. The elapsed timer of the quiz will not run
3. Refresh the Congrea
4. Timer will start running
![quiz elapsed](https://user-images.githubusercontent.com/38027574/62854396-da39f780-bd0c-11e9-97d6-83d651ee2c63.PNG)

**Comment by bogatisuman** [comment]
Fixed at https://github.com/bogatisuman/virtualclass/commit/0cedee8abb689b778f9e09f90e219d762786b65a
