### ISSUE TITLE
Issue with poll result

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#1193]
1. Publish the poll
2. All the users will give their vote
3. Now teacher end the poll manually

Results:
Teacher will not get result
![Screenshot from 2019-08-12 16-50-43](https://user-images.githubusercontent.com/38027574/62861684-e11f3500-bd21-11e9-92b0-9d4944468738.png)

**Comment by meevm** [comment]
Poll results were visible to the teacher
![Screenshot from 2019-08-13 10-42-08](https://user-images.githubusercontent.com/12167050/62916757-61dc4080-bdb7-11e9-9385-f6bff0bccd4d.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
Poll result won't display at teacher side on completely closing of poll.
