### ISSUE TITLE
Video sharing: A non functional Live button displaying additionally. 

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1196]
There is a non functional button **"LIVE"** displaying additionally in video player:

![Screenshot from 2019-08-13 11-09-25](https://user-images.githubusercontent.com/36185596/62917709-fac08b00-bdba-11e9-97fa-345ae458b7cd.png)

**Comment by bogatisuman** [comment]
Fixed at https://github.com/bogatisuman/virtualclass/commit/976ae50dc9fa4c9d05e256e8a86f50fbd82fdd8a
