### ISSUE TITLE
Helpppp

### ISSUE THREAD

**Issue by mdabhn** [congrea/virtualclass#1222]
I couldn't able to run the project..
Any help to start the project locally ?

**Comment by bogatisuman** [comment]
Download virtualclass (Congrea Virtual Classroom) repository from https://github.com/congrea/virtualclass,


If you are using xampp as a local server, you are required to place virtualclass folder in htdocs folder. 

If you are using apache in linux OS, you are required to place virtualclass folder in your html folder.

Edit your hosts which can be found 

At Window, C:\Windows\System32\Drivers\etc\hosts, or

At linux, /etc/hosts,

Now, add below line,

yourIpAddress live.congrea.net

and replace yourIpAddress with your ip address

Run below urls on different browser

Url for teacher :-
https://live.congrea.net/virtualclass/example/index1.php?id=148&role=t&name=teacher&room=98787&play=false&themecolor=gray

Url for student :-
https://live.congrea.net/virtualclass/example/index1.php?id=123&role=s&name=student&room=98787&play=false&themecolor=gray
