### ISSUE TITLE
Issue with the Poll report on mobile

### ISSUE THREAD

**Issue by ANSHU2401** [congrea/virtualclass#1249]
1. Publish poll and end the poll
2. Now on student side the report appears
3. Collapse the right bar and refresh the tab
4. No expand the right bar
Result:
![Screenshot from 2019-11-05 14-15-42](https://user-images.githubusercontent.com/38027574/68192735-c8988100-ffd7-11e9-9dad-0bcfe8685562.png)

**Comment by bogatisuman** [comment]
https://github.com/bogatisuman/virtualclass/commit/be334c72e182bbb785c00ac7f24fb6e9f1eb5333
