### ISSUE TITLE
Play/Pause button on youtube video at student side.

### ISSUE THREAD

**Issue by bogatisuman** [congrea/virtualclass#125]
There is a Play/Pause button on youtube video at student side.

**Comment by meevm** [comment]
Play/Pause button is not there on student screen anymore. But if the teacher has paused the video the student can still play it by refreshing his screen and clicking the continue button (while its still paused at teacher's screen).

**Comment by meevm** [comment]
Now the student has play button at his end when the teacher pauses the video.
