### ISSUE TITLE
Issue with hand raise.

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1252]
1. Join a session a student
2. Do hand raise
3. Teacher and student refreshes the window at the same time the count of the hand raise is effected
![Screenshot from 2019-11-05 15-35-04](https://user-images.githubusercontent.com/38027574/68198356-dbb04e80-ffe1-11e9-89b2-cc3edfca30fd.png)

**Comment by suman** [comment]
Hand raised is merged with Ask Question feature.
