### ISSUE TITLE
Whiteboard Text box / text size issue

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1289]
Text box / text size issue: while using Whiteboard when faculty select Text, the text box appear in the white board but after typing some alphabets when tap outside the text box the alphabets showing bigger than the actual size
![Screenshot from 2020-01-27 14-49-29](https://user-images.githubusercontent.com/38027574/73172705-a2433700-4129-11ea-80e9-b73d031c6451.png)
![Screenshot from 2020-01-27 14-49-19](https://user-images.githubusercontent.com/38027574/73172708-a3746400-4129-11ea-81b8-c729ab482ec6.png)

**Comment by suman** [comment]
Whiteboard bugs are fixed by integrating new version of fabric.js.
