### ISSUE TITLE
Tool tip needs to be added on the icon appears with the question

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1294]
![screenshot-live congrea net-2020 01 31-14_54_25](https://user-images.githubusercontent.com/38027574/73527763-a200af80-4439-11ea-8b9b-6112311bb902.png)

**Comment by Rohitsharma2019** [comment]
Resolve
https://github.com/Rohitsharma2019/virtualclass/commit/1b30fa6710c4f5ff5e5574d53454fc61b76f13a6
