### ISSUE TITLE
"Un-mark as answer is not working" if teacher replied to the answer also sting needs to corrcted

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1295]
1. Join a session and student create question
2. Teacher answer's the question and as per the functionality the answer would be marked as answer by default but on the answer's option still "Mark as answer" option appears instead of "Unmark answer"
![Screenshot from 2020-01-31 16-22-22](https://user-images.githubusercontent.com/38027574/73534274-c0b97300-4446-11ea-9032-64eb5d17ceb3.png)

The button "Unmark as answer is not working" as it's not unmarking the answer

**Comment by Shubhamvaishala** [comment]
Fixed
