### ISSUE TITLE
Mark & Note setting button is not functioning properly

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1297]
1. Join a session
2. Go to setting tab, there you will see Mark & Note is disabled
Results: Notes at student window is enabled
![Screenshot from 2020-02-03 11-38-07](https://user-images.githubusercontent.com/38027574/73629605-b337ff00-4679-11ea-9735-7b2baa1e7885.png)

**Comment by Shubhamvaishala** [comment]
Fixed
