### ISSUE TITLE
Up-vote is not working fine

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1299]
1. Join a session with 4-5 users
2. Now 1 user will ask a question
3. Other user will click on up-vote icon and refresh the tab

Results: After page loads user will be able to up-vote once again
![Screenshot from 2020-02-03 15-45-14](https://user-images.githubusercontent.com/38027574/73645262-f6579980-469c-11ea-93f2-9422eea35a55.png)
![Screenshot from 2020-02-03 15-45-22](https://user-images.githubusercontent.com/38027574/73645263-f6579980-469c-11ea-911d-351d4064cf67.png)

**Comment by Shubhamvaishala** [comment]
Fixed 
https://github.com/Shubhamvaishala/virtualclass/commit/73e8bb9c6a3b850348c56d947f4e4fa8f44c0deb
