### ISSUE TITLE
Text area should be increased

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1309]
Text area needs to be increased for the desktops.
Current:
![Screenshot from 2020-02-04 11-39-26](https://user-images.githubusercontent.com/38027574/73718700-4852fa80-4743-11ea-9355-b2f84e265e05.png)

Expected:
![Screenshot from 2020-02-04 11-39-38](https://user-images.githubusercontent.com/38027574/73718709-4e48db80-4743-11ea-94f1-c02eadf42f29.png)

**Comment by Rohitsharma2019** [comment]
as discussed with udit no need to increased text area
