### ISSUE TITLE
Mark as answer option snot appearing in recording

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1314]
1. Play a recorded session
2. If any student answer a question during the recording.
3. Go to the option to mark it as answer but this option not appears in the recording for the teacher
![Screenshot from 2020-02-04 15-00-37](https://user-images.githubusercontent.com/38027574/73731790-1fd8f980-475f-11ea-9aac-b86b9d809d49.png)

**Comment by Shubhamvaishala** [comment]
Fixed,
https://github.com/Shubhamvaishala/virtualclass/commit/9d899834541354982db78354856298923f4acd8b
