### ISSUE TITLE
Not able to edit or any question/answer//comment in recording

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1316]
1. Play a recording
2. Now ask question, answer some other question and comment on other's answer and comment
3. Now go to edit to every answer, comment or asked question, there edit and delete option appears but not functional
![Screenshot from 2020-02-04 15-00-37](https://user-images.githubusercontent.com/38027574/73732508-4a778200-4760-11ea-8a8f-c6cd7d4ea7b4.png)

**Comment by Shubhamvaishala** [comment]
Fixed,
https://github.com/Shubhamvaishala/virtualclass/commit/8d8fc519750ca3078b0e428b5bc960587702e564
