### ISSUE TITLE
Tab switching is not working properly

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1319]
1. Go to user list/common chat/Q&A
2. Not open pre-check
3. Switch to Notes/Q&A

Result:
![Screenshot from 2020-02-05 12-01-48](https://user-images.githubusercontent.com/38027574/73817787-d8f80c00-4811-11ea-9f45-1bc0fb172805.png)
![Screenshot from 2020-02-05 12-02-24](https://user-images.githubusercontent.com/38027574/73817793-dc8b9300-4811-11ea-8e03-ec2108dcbf2d.png)

**Comment by suman** [comment]
Fixed at https://github.com/suman/virtualclass/commit/5246787f8355cb0b218e123993ef3159bfde38ec
