### ISSUE TITLE
Two tabs selected at same time

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1325]
1. Join a session
2. Go to notes/Q&A
3. Now receive message from other user on common chat and switch the tab to common chat
Results:
![Screenshot from 2020-02-06 16-44-42](https://user-images.githubusercontent.com/38027574/73933237-04f2ba80-4902-11ea-8483-f24664a23300.png)

**Comment by suman** [comment]
It was fixed in code.
