### ISSUE TITLE
Icon s not appearing properly if any user ask question

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1326]

**Comment by sudhanshu0044** [comment]
1. Join a session
2. Any user ask a question
3. Now every user receive a notification on their devices(desktop, iOS)
4. Now icon get dislocated once the icon get highlighted
![Screenshot from 2020-02-07 10-22-28](https://user-images.githubusercontent.com/38027574/74002216-6ebba480-4994-11ea-8603-5ca3b5d1cccd.png)

**Comment by Rohitsharma2019** [comment]
issue resolved
