### ISSUE TITLE
Notification colours are different

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1327]
1. ask a question
2. Now write something on common chat
Result:
![Screenshot from 2020-02-07 10-23-09](https://user-images.githubusercontent.com/38027574/74002392-f3a6be00-4994-11ea-9cb3-de6149fa73fa.png)

**Comment by uditbh** [comment]
Will change soon. We will notify by other way

**Comment by Rohitsharma2019** [comment]
issue resolved
