### ISSUE TITLE
Note icon is note appearing

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1328]
1. Join a session on Asus phone
Result:
1. Note icon not appeared
![touchmaster_1581051970369](https://user-images.githubusercontent.com/38027574/74002774-459c1380-4996-11ea-8cae-8f551bd97803.jpeg)

**Comment by uditbh** [comment]
This was not running by your local machine. Retry it once

**Comment by sudhanshu0044** [comment]
checked working fine
