### ISSUE TITLE
Tab names are not appearing properly

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1329]
1. Join session on Asus phone
2. Switch to every tab

Result: 
![touchmaster_1581051112213](https://user-images.githubusercontent.com/38027574/74002854-809e4700-4996-11ea-9dae-f7664e6f01a3.jpeg)
![touchmaster_1581051958391](https://user-images.githubusercontent.com/38027574/74002858-81cf7400-4996-11ea-975a-08e7d7ae17bc.jpeg)
![touchmaster_1581051970369](https://user-images.githubusercontent.com/38027574/74002859-82680a80-4996-11ea-8865-d79129884692.jpeg)

**Comment by uditbh** [comment]
This was not running by your local machine. Retry it once

**Comment by sudhanshu0044** [comment]
checked, working fine
