### ISSUE TITLE
Issue with white board canvas

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1331]
1. Join a session
2.Create a new page
3. Try to draw a shape or anything on page

Results:
![Screenshot from 2020-02-07 14-25-49](https://user-images.githubusercontent.com/38027574/74122245-78d9df00-4bf0-11ea-850f-0d8d4ee1cfde.png)

**Comment by suman** [comment]
Whiteboard bugs are resolved by integrating new version of fabric.js.
