### ISSUE TITLE
Edit and delete option should not appear once the 30 min is passed after refresh

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1338]
1. Join a session(As student)
2. Ask a question
3. After 30 mins passes, go to edit/delete option as after clicking on any option these option gets disappeared when notification appears
4. Refresh the tab
Result: Option to delete and edit appears again
![Screenshot from 2020-02-13 14-18-38](https://user-images.githubusercontent.com/38027574/74416857-bdbd7a00-4e6b-11ea-8771-cd6ad487342b.png)

**Comment by Shubhamvaishala** [comment]
Fix bug,
https://github.com/Shubhamvaishala/virtualclass/commit/359e51ce2da716e304010e6fce9f170652e13579
