### ISSUE TITLE
Uploaded videos are not being played on android phones

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1355]
1. Join a session from android phone
2. Upload a .mp4 file and start video sharing
3. On other devices video starts playing but on android result given below:
![Screenshot from 2020-03-06 14-17-04](https://user-images.githubusercontent.com/38027574/76067659-c0684680-5fb5-11ea-8ea8-19155c54be87.png)

**Comment by Shubhamvaishala** [comment]
duplicate issue: #1253
