### ISSUE TITLE
Issue with the right bar

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1372]
1. Collapse the right bar
2. Refresh the tab
Result: Right bar gets expanded as it should be in same state "collapse"
Error on console
![Screenshot from 2020-03-19 12-23-41](https://user-images.githubusercontent.com/38027574/77039975-0ae9ba00-69dd-11ea-92d6-98216a52abf6.png)

**Comment by Shubhamvaishala** [comment]
Not reproduced
