### ISSUE TITLE
Not able to delete or edit the question

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1373]
1. Join session(as student and teacher)
2. Go to ask question tab
3. Go to document share and share a document file
4. Ask a question
5. Refresh the tab 
6. Try to edit or delete it
Result: Option button is not responding(only desktop)
![Screenshot from 2020-03-19 12-51-41](https://user-images.githubusercontent.com/38027574/77041898-b8aa9800-69e0-11ea-9b6d-7a9327606133.png)

**Comment by Shubhamvaishala** [comment]
Fix issue https://github.com/Shubhamvaishala/virtualclass/commit/7d85223b066957fa4f794ee435d94af5841b6253
