### ISSUE TITLE
Issue with the note in recording

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/virtualclass#1374]
1. Do a session and write some notes in 2-3 pages
2. Play the recording
3. Now go to notes and navigate it
Result: Notes will stop appearing as below and error on console is displayed
![Screenshot from 2020-03-19 15-26-51](https://user-images.githubusercontent.com/38027574/77054713-172e4100-69f6-11ea-9ee5-09dcd32c928e.png)
![Screenshot from 2020-03-19 15-26-56](https://user-images.githubusercontent.com/38027574/77054725-185f6e00-69f6-11ea-856a-44923c7723e9.png)

**Comment by Shubhamvaishala** [comment]
Not reproduced
