### ISSUE TITLE
Add Session issue 

### ISSUE THREAD

**Issue by prinsapps** [congrea/virtualclass#1402]
Adding new session not visible in chrome, and the block keeps blinking, but adding a session
works fine in Firefox browser

![Live_Session_and_Live_Session_and_New_Issue_·_congrea_virtualclass](https://user-images.githubusercontent.com/44002379/83824992-ee9e1500-a6cf-11ea-8168-80d5ad3a4c1f.png)

**Comment by jgupta** [comment]
Closing this from this repo. It would be taken care of at Congrea Moodle plugin repo.

https://github.com/congrea/moodle-mod_congrea/issues/113
