### ISSUE TITLE
The long text is hiding behind the audio block at right side and windows of chats.

### ISSUE THREAD

**Issue by bogatisuman** [congrea/virtualclass#144]
The long text is hiding behind the audio block at right side and windows of chats.

**Comment by meevm** [comment]
The issue still exist.
![Screenshot from 2019-06-26 10-40-38](https://user-images.githubusercontent.com/12167050/60152693-1ec21000-97ff-11e9-97d3-590d8558d584.png)
![Screenshot from 2019-06-26 10-41-32](https://user-images.githubusercontent.com/12167050/60152695-21246a00-97ff-11e9-89ff-ab250fcd4b06.png)

**Comment by jgupta** [comment]
Not a bug (assuming that it is a private chat that is hiding main content). It is expected that the user would close private chat to see the content.
