### ISSUE TITLE
There may be the problem when student's continuous editor writing while teacher does refresh the page at other side .

### ISSUE THREAD

**Issue by bogatisuman** [congrea/virtualclass#161]
There may be the problem when student's continuous editor writing while teacher does refresh the page at other side .

This is not happens each time but rarely.

**Comment by meevm** [comment]
The problem still exist. When the teacher has given editing rights to students on text editor and teacher refreshes the screen, if one student keeps on writing its not appearing on other student or teacher screen . 
![Screenshot from 2019-06-26 10-29-15](https://user-images.githubusercontent.com/12167050/60152347-be7e9e80-97fd-11e9-8e27-2f6dd4bee5b7.png)

**Comment by meevm** [comment]
Even when the presenter clears the entire screen on text editor, the text still appears on student's screen. The sink gets broken.
![Screenshot from 2019-06-26 10-35-20](https://user-images.githubusercontent.com/12167050/60152501-5e3c2c80-97fe-11e9-9211-0f9c936b2c64.png)
