### ISSUE TITLE
In rare case, two users are try to join as teacher but can not.

### ISSUE THREAD

**Issue by bogatisuman** [congrea/virtualclass#200]
We set the variable time for requesting teacher role in each user.
If two user apply for teacher role at the same time, we are checking that if there teacher is already existing, If found we convert later user to student. 

In normal case,  If a user is joined as teacher and found if there is already teacher is existing in room then the user  would join as student. But in rare case there  are joining both users  as teacher because other teacher role is not found when checking against this teacher role during the request teacher role.

**Comment by meevm** [comment]
'Become a teacher' feature is not available now.
