### ISSUE TITLE
Private chat boxes with many users are not aligning well

### ISSUE THREAD

**Issue by meevm** [congrea/virtualclass#230]
If the number of private chats increase, the chat boxes doesn't adjust well...and overlap each other.

**Comment by meevm** [comment]
The problem still exist.
![Screenshot from 2019-06-26 12-21-58](https://user-images.githubusercontent.com/12167050/60157798-37d1bd80-980d-11e9-937a-a2ad730b200a.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
Duplicate of https://github.com/congrea/virtualclass/issues/1098
