### ISSUE TITLE
Not showing the latest page on participate when teacher role is assigned

### ISSUE THREAD

**Issue by bogatisuman** [congrea/virtualclass#235]
There is not showing the latest app on participate side when the presenter change the app during the  participate's joining.
For example, if presenter is in rich editor, one of the participate does page refresh, presenter does select the code editor meanwhile. There participate is still on rich editor. The app window would remain same until the presenter select the other app.

This happens only when teacher role is assigned to other user.  It works fine in normal case.

**Comment by meevm** [comment]
Role assigning feature is not available now.
