### ISSUE TITLE
Use requestAnimationFrame instead of setTimeout/setInterval

### ISSUE THREAD

**Issue by bogatisuman** [congrea/virtualclass#237]
For performance and battery, We can use the [requestAnimationFrame()](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) instead of setTimeout()/setInterval().

We can get more information with https://www.paulirish.com/2011/requestanimationframe-for-smart-animating/.

**Comment by jgupta** [comment]
Limitations of requestAnimationFrame()

1. Does not have fine control over time.
2. Delay will increase if browser tab is inactive.

Which parts do you propose to replace?

**Comment by bogatisuman** [comment]
I was thinking for screen sharing part.  Does second point means, it increases the delay after browser went inactive to active ?  

Is not good, if the screen-sharing would be interrupted while browser tab is inactive ? The application sends the data 1 frame per second with setInterval case if browser tab is inactive.

**Comment by jgupta** [comment]
https://dbaron.org/log/20100309-faster-timeouts
https://dbaron.org/mozilla/zero-timeout
