### ISSUE TITLE
Document sharing, lengthy file name (if contains underscore '_') affects UI.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#731]
Lengthy file name (only when file name contains underscore ‘_’ ) affecting UI after upload (screen resolution 1024x768):
![screenshot from 2018-07-13 11-45-20](https://user-images.githubusercontent.com/36185596/42675878-7b998fb6-8693-11e8-9c20-7a406f471716.png)
![screenshot from 2018-07-13 11-45-36](https://user-images.githubusercontent.com/36185596/42675879-7bc39de2-8693-11e8-9c86-7146ac07a528.png)
![screenshot from 2018-07-13 11-52-37](https://user-images.githubusercontent.com/36185596/42675880-7becc096-8693-11e8-9063-25233970537c.png)
![screenshot from 2018-07-13 11-52-41](https://user-images.githubusercontent.com/36185596/42675882-7c177b38-8693-11e8-9b71-e3391edc1473.png)

**Comment by uditbh** [comment]
Already fixed
