### ISSUE TITLE
After document/ video upload, during the processing if page refreshed, the processing not displayed.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#733]
After document /video uploaded, during the processing document /video at the same time if page refreshed:

Document displayed like processed but becomes unclickable & processing in background
After upload under processing:
![screenshot from 2018-07-13 12-44-01](https://user-images.githubusercontent.com/36185596/42677843-aeb67088-869a-11e8-9267-76498924177e.png)
After refresh it's unclickable:
![screenshot from 2018-07-13 12-44-25](https://user-images.githubusercontent.com/36185596/42677842-ae7d0a5a-869a-11e8-869c-afe40dfe7f63.png)

Video disappears from video files list and appears after a few moments like this:
After upload under processing:
![screenshot from 2018-07-13 12-48-30](https://user-images.githubusercontent.com/36185596/42677972-148037f0-869b-11e8-8194-83cd5eb1b6fd.png)
After refresh video disappears & displayed when it completely processed in background.

**Comment by Sudhanshu0044** [comment]
1. Upload document file and while processing refresh the Congrea tab
Results: The uploaded document is not selectable 
Video sharing is working fine.

**Comment by Sachi01** [comment]
Reproduced

**Comment by bogatisuman** [comment]
On page refresh, the link of video and document on left side is not available unless video/document would be converted 

For example, If you upload the video/document and do the page refresh same time, the link is not available, now suppose video/document is converted, and again you do the page refresh, then  the link is available this time.
