### ISSUE TITLE
Whiteboard /Document sharing: Text box able to edit an previous written text.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#734]
In Whiteboard /Document sharing, if select the text box & click on previously written text, it becomes editable:

**Written text:**
![screenshot from 2018-07-13 12-52-37](https://user-images.githubusercontent.com/36185596/42678324-2d0efc9c-869c-11e8-9855-06647af0d855.png)

**After click on previously written text:**
![screenshot from 2018-07-13 12-52-52](https://user-images.githubusercontent.com/36185596/42678275-0842b872-869c-11e8-81b4-810b96a45e72.png)

**Comment by Shubhamvaishala** [comment]
This is not a bug. we giving editable facility.
