### ISSUE TITLE
If quiz layout is multiple questions per page & navigate to next page the bottom position displayed of the next page.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#736]
If teacher has set the layout 5 questions per page and student click on next page, the page should display from top position. But it display the bottom position after clicking next:
![screenshot from 2018-07-13 14-16-54](https://user-images.githubusercontent.com/36185596/42682174-6909aae8-86a7-11e8-8556-fb4fc9d46204.png)

**Comment by uditbh** [comment]
This is major enhancement, will do this later
