### ISSUE TITLE
Quiz: If directly switch to any question, the Back button disappears.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#737]
If student directly switch to any question, the Back button disappears. When click next, the back button displayed again:

![screenshot from 2018-07-13 14-19-01](https://user-images.githubusercontent.com/36185596/42682266-b64bd4f2-86a7-11e8-9b19-c6a8cbbcaf79.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
This is the limitation  of sliqquiz, the quiz does not create the back button when you switch the question through the quiz navigation directly.
