### ISSUE TITLE
Quiz: after submit two types of reports generated at student side.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#740]
When student submit the quiz, he gets the result in below format:
![screenshot from 2018-07-13 15-52-11](https://user-images.githubusercontent.com/36185596/42686828-bb20fd56-86b4-11e8-9ecc-35b602dd3c55.png)

But after refresh the screen at the same time, the reports changed to this format:
![screenshot from 2018-07-13 15-52-51](https://user-images.githubusercontent.com/36185596/42686858-d0babcf6-86b4-11e8-97bc-4648cb86a6fb.png)

Either only one format of result should be displayed or the second format should only visible when quiz closed (by teacher or by timer).

**Comment by Shubhamvaishala** [comment]
UI issue

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by Shubhamvaishala** [comment]
https://github.com/Shubhamvaishala/virtualclass/commit/73f9ae90c168b52e5b276a7e0b33344230157a08
