### ISSUE TITLE
Text Editor: The controls are hiding with resolution 1200x800 & 1024x768.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#742]
**Teacher Side:**
1200x800:
![screenshot from 2018-07-13 17-33-45](https://user-images.githubusercontent.com/36185596/42690689-edc9a240-86c2-11e8-9c8f-9c7b6b6d1470.png)

1024x768:
![screenshot from 2018-07-13 17-34-13](https://user-images.githubusercontent.com/36185596/42690697-fb23b67e-86c2-11e8-9b82-6e268a878afd.png)

**Student Side:**
1200x800 Not hiding any icon:
![screenshot from 2018-07-13 17-35-21](https://user-images.githubusercontent.com/36185596/42690748-25138004-86c3-11e8-8d84-c98f7c62810b.png)

1024x768:
![screenshot from 2018-07-13 17-35-47](https://user-images.githubusercontent.com/36185596/42690769-3368d6fe-86c3-11e8-8149-aa99321a4fdf.png)

**Comment by uditbh** [comment]
Tools will be grouped soon

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
