### ISSUE TITLE
Video sharing: volume button affecting the UI (video progress bar):

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#754]
During the video sharing, if hover the cursor on volume button it affects the video progress bar and the volume controller position is also not proper:

![screenshot from 2018-07-18 17-21-50](https://user-images.githubusercontent.com/36185596/42879676-145afdf6-8aaf-11e8-94f6-ee656eb16a34.png)

**Comment by benchakino** [comment]
Hey? How you implement this? Please help me

**Comment by uditbh** [comment]
closed
