### ISSUE TITLE
Video Sharing: New user getting an error when youtube video shared.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#849]
When new user join the class & teacher had shared the youtube video. User is getting an error on screen for 4-5 seconds & then video loads to play. 
Sometimes it stay on error page and doesn't proceed to play the video.

Screenshot attached herewith:
![screenshot from 2018-09-18 12-56-54](https://user-images.githubusercontent.com/36185596/45671184-6d40d080-bb42-11e8-92e2-77902427e152.png)

**Comment by Sudhanshu0044** [comment]
Not reproduced
