### ISSUE TITLE
Document Sharing: Document thumbnails not loading after browser restart.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#850]
When teacher is present on document dashboard & restart the browser, the document thumbnails doesn't load & the console error 403 produced. 

Screenshot attached herewith:
![screenshot from 2018-09-19 11-26-27](https://user-images.githubusercontent.com/36185596/45733632-1d740f00-bbff-11e8-97b4-bfd9780c4bd3.png)

![screenshot from 2018-09-19 11-24-09](https://user-images.githubusercontent.com/36185596/45733635-21079600-bbff-11e8-82bc-b16f5d5070bc.png)

**Comment by Sudhanshu0044** [comment]
Not reproduced
