### ISSUE TITLE
Whiteboard: New user join not getting the data.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#852]
If teacher is present on whiteboard & a new user join the class, the whiteboard objects appears for a few mili seconds and then blank page appears only. 
After refresh also blank page appears but after refresh clicking on reload whiteboard produces an error in console:

![screenshot from 2018-09-19 14-26-50](https://user-images.githubusercontent.com/36185596/45742614-0ee62180-bc18-11e8-8c85-4150c03fb35c.png)

**Comment by Shubhamvaishala** [comment]
Not reproduce
