### ISSUE TITLE
Video Sharing: Console error when new user join the class.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#854]
During the video sharing, if new user join the class. The video plays properly but an error occured in console:

![screenshot from 2018-09-19 15-23-14](https://user-images.githubusercontent.com/36185596/45746136-26c1a380-bc20-11e8-8764-b47834c973ee.png)
![screenshot from 2018-09-19 15-22-47](https://user-images.githubusercontent.com/36185596/45746138-26c1a380-bc20-11e8-8882-4e32b95dc0eb.png)

**Comment by Sudhanshu0044** [comment]
Not reproduced
