### ISSUE TITLE
Local machine

### ISSUE THREAD

**Issue by ph4t0o0o0om** [congrea/virtualclass#864]
How to install this to my local machine and run on my local server?

**Comment by Shubhamvaishala** [comment]
Download virtual class (Congrea Virtual Classroom) repository from https://github.com/vidyamantra and after that paste into your local server.

If you are using xampp as a local server, you are required to place virtual class folder in htdocs folder. If you are using apache in linux OS, you are required to place virtual class folder in your html folder. 

Go to (virtualclass/example/index1.php , line no :- 57), change path (replace this https://local.vidya.io/virtualclass/  to  https://localhost/virtualclass/). If the name of your server is localhost, write  https://localhost/virtualclass/ or if server name is xyz write  https://xyz/virtualclass/

Url for teacher :-
https://localhost/virtualclass/example/index1.php?id=148&role=t&name=teacher&room=10&play=false&themecolor=gray&pushtotalk=1&anyonepresenter=0&wnr=0#

Url for student :-
https://localhost/virtualclass/example/index1.php?id=123&role=s&name=student&room=10&play=false&themecolor=gray&pushtotalk=1&anyonepresenter=0&wnr=0#

**Comment by bogatisuman** [comment]
If there is any problem, please reopen the ticket.

**Comment by ph4t0o0o0om** [comment]
I tried your comment I follow the steps but nothing happens. The browser is keep on reloading and reloading. How to fix this? Thank you!

**Comment by bogatisuman** [comment]
Can you please see if any error is coming on browser console ? If yes, please provide the screen-shot of this error, and also send the screen shot your screen.

**Comment by ph4t0o0o0om** [comment]
Okay. But one thing . Do I need API's keys? Or this is a 100% open source
software? Even if the signaling server?

**Comment by bogatisuman** [comment]
Yes you need a license key to run Congrea, you can get this key from our website https://www.congrea.com/. The front-end is 100% open source, we only charge for back end service (signalling server). We also offering free trail for one year with limited users.

Anything you want to know, please let us know.

**Comment by ph4t0o0o0om** [comment]
Awrigh. But is it possible to run this on node.ks socket.io signaling
server? Because I have here.

**Comment by bogatisuman** [comment]
Yes it can be run with node.js signalling server.

**Comment by ph4t0o0o0om** [comment]
Do you have sample source code? For node.js signaling server? I just going
to check if my server is applicable

**Comment by ypshukla** [comment]
As of now, the sample code for node.js is not available.
