### ISSUE TITLE
Text editor: Text selected automatically.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#888]
When teacher turn on the collaboration mode, student write some text and select all text. 
After that if teacher write any text, the new written text also selected automatically (either collaboration on or off)

![screenshot from 2018-10-12 14-17-20](https://user-images.githubusercontent.com/36185596/46858793-bc201400-ce29-11e8-8f5e-cc84d687dc4b.png)
![screenshot from 2018-10-12 14-17-57](https://user-images.githubusercontent.com/36185596/46858798-bf1b0480-ce29-11e8-9592-57f5539dea36.png)

**Comment by jgupta** [comment]
Not an bug.
