### ISSUE TITLE
Poll: Graph display (sorting order) issue with numerical options.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#897]
If poll published with some numerical options, the graph doesn't display the options in sequence (as published). It sort the options in increasing order.

![screenshot from 2018-10-27 17-18-56](https://user-images.githubusercontent.com/36185596/47603625-6e500200-da0c-11e8-94e0-e862d0646381.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
This problem is fixed with update of **c3.js'** new version (v0.7.8).
https://github.com/bogatisuman/virtualclass/commit/378e431870c78b8241a9360ea96c24772e6e4184
