### ISSUE TITLE
Delete button should be highlighted for disabled ppt /video.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#898]
**Video sharing & Presentation sharing:**

If some video or presentation is disabled, the disabled button should be highlighted.

![screenshot from 2018-10-27 17-31-09](https://user-images.githubusercontent.com/36185596/47603759-1ca87700-da0e-11e8-9c2b-61b8b94f9401.png)

**Comment by uditbh** [comment]
closed
