### ISSUE TITLE
Desktop Selector: The install instructions and snapshots are missing at Desktop selector page.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#899]
If a user doesn't have installed the Desktop selector & during the request screen share, the Desktop selector window opens. It doesn't contain any install instructions & there are no snapshots uploaded.
There should be a message reflected to install and reload the page like below:

![screenshot from 2018-10-30 11-40-00](https://user-images.githubusercontent.com/36185596/47699403-ccf9c380-dc38-11e8-97f8-a2b4097d6794.png)

Adding the snapshots would be better:
![screenshot from 2018-10-30 11-42-40](https://user-images.githubusercontent.com/36185596/47699439-f0247300-dc38-11e8-86e6-b60fa153de30.png)

**Comment by Shubhamvaishala** [comment]
no issue
