### ISSUE TITLE
Document Share: "Drop files here" message displayed behind the tiles.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#903]
If teacher is present on document dashboard & end the session. After that visiting again on Document dashboard, the **"Drop files here"** message displayed behind the document tiles.

![screenshot from 2018-10-31 12-24-01](https://user-images.githubusercontent.com/36185596/47771079-e3bb1b80-dd07-11e8-8e35-0b4971bccf5f.png)

**Comment by Shubhamvaishala** [comment]
Not reproduce

**Comment by ypshukla** [comment]
When teacher join but not stabled & immediately switch to document sharing, the message **"Drop files here"** appears behind the selected document.

**Comment by Sachi01** [comment]
Reproduced
