### ISSUE TITLE
User's list: During hover on user icon, the username initials displayed with an underline.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#904]
If user's web cam has been turned off & hover on user icon, the username initials displayed with an underline.

![screenshot from 2018-10-31 12-37-02](https://user-images.githubusercontent.com/36185596/47771608-ffbfbc80-dd09-11e8-881e-13105c58cdd9.png)

**Comment by Shubhamvaishala** [comment]
fixed

**Comment by Sudhanshu0044** [comment]
Not reproduced

**Comment by bogatisuman** [comment]
This bug does not exist any more in new bug.
