### ISSUE TITLE
Quiz: Grade report is not visible in proper format.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#906]
**There is a term "undefined" mentioned in grade report & tabs are highlighted with grey:**

![screenshot from 2018-11-13 17-12-54](https://user-images.githubusercontent.com/36185596/48412244-1df5d580-e76a-11e8-8ff9-58a99e2905ab.png)

**Comment by uditbh** [comment]
I resolved the highlighted tabs UI, and the term undefined in the userlist is pending

**Comment by Shubhamvaishala** [comment]
Fix
