### ISSUE TITLE
Quiz: Student's response clear after refresh.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#912]
If student attempted a few questions and page refreshed. After page refresh, all responses cleared from the attempted questions. 
It should be saved after refresh also.

**Comment by Sudhanshu0044** [comment]
Students' response:
![Screenshot from 2019-07-09 11-19-58](https://user-images.githubusercontent.com/38027574/60862564-8c2c6280-a23b-11e9-9249-51b9e0ccd630.png)

Students' result:
![Screenshot from 2019-07-09 11-20-12](https://user-images.githubusercontent.com/38027574/60862563-8c2c6280-a23b-11e9-988c-feacbf48bd0d.png)

**Comment by Sudhanshu0044** [comment]
After publishing quiz refresh the page
![Screenshot from 2019-07-09 11-22-25](https://user-images.githubusercontent.com/38027574/60862689-f513da80-a23b-11e9-808e-3c0bbd92a160.png)

**Comment by Sudhanshu0044** [comment]
Duplicate issue https://github.com/congrea/virtualclass/issues/738
