### ISSUE TITLE
"Webcam is not initialized properly" This message shouldn't be displayed if webcam not plugged in.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#913]
If webcam is not present at the system (not plugged in), the message **"Your webcam is not initialized properly. Please reload the page."** shouldn't be displayed.

![screenshot from 2018-12-13 17-20-04](https://user-images.githubusercontent.com/36185596/49936970-5ddfe200-fefb-11e8-9b94-37cdfbda2780.png)

**Comment by Sudhanshu0044** [comment]
Not reproduced
