### ISSUE TITLE
Presentation: New user join, duplicate congrea session in the canvas.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#914]
When teacher is present on presentation & a new user join the class. A duplicate congrea session opens on his canvas.

![screenshot from 2018-12-14 10-10-14](https://user-images.githubusercontent.com/36185596/49983619-cecddb00-ff89-11e8-8fda-55b92af15620.png)

**Comment by bogatisuman** [comment]
Solved.
