### ISSUE TITLE
Screenshare: Teacher is able to request screenshare multiple students at a time.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#915]
Teacher is able to request screenshare with multiple students. If both student share the screen, following error occurred in console:

![screenshot from 2018-12-14 11-44-01](https://user-images.githubusercontent.com/36185596/49986393-c4b1d980-ff95-11e8-9af4-f5b8ece314b6.png)

**Comment by Shubhamvaishala** [comment]
#915 Fix
