### ISSUE TITLE
Poll: After unattempted poll, student side only message should be displayed.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#917]
If student doesn't attempt the poll & poll closed. The below message appears:
![screenshot from 2019-01-09 14-14-39](https://user-images.githubusercontent.com/36185596/50887483-44a65480-1419-11e9-9667-e986e1684b5a.png)

The poll options shouldn't be displayed after unattempted poll.

**Comment by Sudhanshu0044** [comment]
Not reproduced
