### ISSUE TITLE
Quiz: Grade report contains some unwanted character "undefined".

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#918]
When students submit the quiz & teacher visits to Grade report tab, the result contains an **undefined** character with the student name:

- The "Questions overview" & "Grade report" tabs UI is also not proper:

![screenshot from 2019-01-30 12-24-00](https://user-images.githubusercontent.com/36185596/51963577-181ab100-248a-11e9-8a6b-f1e4a3c0f5eb.png)

**Comment by Shubhamvaishala** [comment]
Fix
