### ISSUE TITLE
Chat: Private chat & Common chat teacher name differs at student side.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#919]
During the student screen is being refreshed, at the same time if teacher write some text in private chat or common chat. After refresh, the teacher name differs at student side.

Teacher side:
![screenshot from 2019-01-19 17-12-22](https://user-images.githubusercontent.com/36185596/51426234-afbc0c00-1c0d-11e9-9063-aef727e9b89c.png)

![screenshot from 2019-01-19 17-06-34](https://user-images.githubusercontent.com/36185596/51426181-c31aa780-1c0c-11e9-8378-402917020def.png)

Student side (there is **undefined** word displayed at private chat header after refresh):
![screenshot from 2019-01-19 17-12-32](https://user-images.githubusercontent.com/36185596/51426239-ba76a100-1c0d-11e9-9366-9fbf677f24ec.png)

![screenshot from 2019-01-19 17-06-59](https://user-images.githubusercontent.com/36185596/51426183-cdd53c80-1c0c-11e9-825f-96599edf8823.png)

**Comment by Shubhamvaishala** [comment]
Not reproduce
