### ISSUE TITLE
Precheck not working during screenshare & request screenshare.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#920]
If teacher requests screenshare with student & runs his own precheck at the same time. As the screen shared by student, the teacher precheck window closed automatically. After that precheck doesn't open during the screen shared.
If precheck window opened & closed by teacher manually, the student able to see the teacher's video even teacher camera is off.

The same happens if teacher share the screen with student & at the same time student runs his own precheck, the student precheck window closed automatically & doesn't open again.

**Comment by Shubhamvaishala** [comment]
in this bug have some html elements issues on click...Fix
