### ISSUE TITLE
Private chat: User's name first letter should be capital like user's list.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#923]
**During congrea demo, if user name taken in small letters. It's first letter capitalized automatically in user's list & common chat:**

**User's list:**
![screenshot from 2019-01-29 15-18-22](https://user-images.githubusercontent.com/36185596/51899653-7e93c680-23d9-11e9-97a8-472a2938f137.png)

**Common chat:**
![screenshot from 2019-01-29 15-20-52](https://user-images.githubusercontent.com/36185596/51899656-805d8a00-23d9-11e9-897f-26e36dd3d867.png)

**User's list hover should also display the first letter capital:**
![screenshot from 2019-01-30 10-16-09](https://user-images.githubusercontent.com/36185596/51958867-1942e280-2478-11e9-911d-b7644e42cf40.png)

**But the private chat displays the user name in small letters:**
![screenshot from 2019-01-29 15-18-13](https://user-images.githubusercontent.com/36185596/51899757-b1d65580-23d9-11e9-9dd9-0228f111d29d.png)

**Comment by Shubhamvaishala** [comment]
fixed
