### ISSUE TITLE
Teacher's video should be closed after unplug the camera.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#924]
**If teacher's camera unplugged, the video should be turned off. But it displayed a black window on both teacher & student side:**

**Teacher side:**
![screenshot from 2019-01-29 15-46-26](https://user-images.githubusercontent.com/36185596/51901249-34144900-23dd-11e9-94ea-27c6a2010c43.png)

**Student side:**
![screenshot from 2019-01-29 15-47-41](https://user-images.githubusercontent.com/36185596/51901276-44c4bf00-23dd-11e9-80c6-f7076c3649e5.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
