### ISSUE TITLE
Quiz: If quiz not available or hidden, a message should be displayed on congrea Quiz app.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#925]
If there is no quiz activity present in moodle or it's hidden & visit to Congrea -> Quiz app. There a message was displayed previously **"No Quiz available. Congrea supports Multiple Choice questions only."** which is currently not displayed. 

It's blank now:
![screenshot from 2019-01-30 12-27-56](https://user-images.githubusercontent.com/36185596/51963882-e524ed00-248a-11e9-99a1-5ed56f38a78c.png)

**Comment by Shubhamvaishala** [comment]
Fix
