### ISSUE TITLE
Firefox 65.0 Stable version: audio output is missing from settings.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#926]
**Using the Congrea on Firefox latest Stable version 65.0, there is an option **Audio output** is missing from Settings.**
![screenshot from 2019-02-01 11-02-23](https://user-images.githubusercontent.com/36185596/52104923-97d38780-2612-11e9-8234-fd2ee9a93d5f.png)

**But available in Chrome latest stable version 72.0**
![screenshot from 2019-02-01 11-02-15](https://user-images.githubusercontent.com/36185596/52104976-c5203580-2612-11e9-8e2d-82eb010512e7.png)

**Comment by Sudhanshu0044** [comment]
This feature has been removed
