### ISSUE TITLE
Firefox 65.0 stable version: UI issue with whiteboard & document sharing toolbar.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#927]
Using the Congrea with Firefox latest stable version 65.0, the whiteboard & document sharing toolbar UI is affected & not displayed properly:

![screenshot from 2019-02-01 11-18-03](https://user-images.githubusercontent.com/36185596/52105109-60190f80-2613-11e9-81a5-c60e4c3edf5b.png)

**Comment by uditbh** [comment]
closed
