### ISSUE TITLE
Firefox 65.0 stable version: Text editor text selected after refresh.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#928]
**Using Congrea on firefox latest stable version 65.0, if teacher write some text on text editor. After that either teacher or student refresh their window, after refresh the written text displayed as selected:**

**Teacher's window:**
![screenshot from 2019-02-01 14-01-34](https://user-images.githubusercontent.com/36185596/52111520-ee988b80-2629-11e9-816c-69ee31f0701f.png)

**Student's window:**
![screenshot from 2019-02-01 13-58-08](https://user-images.githubusercontent.com/36185596/52111391-9bbed400-2629-11e9-9657-98954ffd75c2.png)

**Comment by Sudhanshu0044** [comment]
Not reproduced
