### ISSUE TITLE
Firefox 65.0 stable version: Whiteboard pagination not displayed properly.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#929]
If draw 4-5 pages in whiteboard & refresh, the pagination looks like below after refresh:
Sometimes it also happens without drawing anything (just screenshare or switch to any app and return to whiteboard):

![screenshot from 2019-02-01 14-14-31](https://user-images.githubusercontent.com/36185596/52112248-f22d1200-262b-11e9-9784-6b850d283041.png)

**Comment by nirmala10** [comment]
fixed. navigation issue also mentioned in #946
