### ISSUE TITLE
Document sharing: When page numbers reaches 3 digits, pagination not diplayed properly.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#931]
If Window size is 1024x768 & teacher present on document sharing: 
When the page number reaches to 3 digits, pagination not displayed properly.

![screenshot from 2019-02-04 12-20-44](https://user-images.githubusercontent.com/36185596/52197357-48e15880-2885-11e9-9c0d-5136cf0b6970.png)

**Comment by nirmala10** [comment]
fixed.
