### ISSUE TITLE
During precheck if not block or allow the camera or microphone popup, the previous and next buttons disappeared.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#932]
During the precheck, if **teacher /student** doesn't **block or allow** the **camera /microphone** popup:
![screenshot from 2019-02-06 10-51-18](https://user-images.githubusercontent.com/36185596/52321942-26724b00-29fd-11e9-8635-c6d7e0a34cea.png)

After proceeding to webcam testing page, the **Previous & Next** buttons disappeared:
![screenshot from 2019-02-06 10-46-06](https://user-images.githubusercontent.com/36185596/52321964-4144bf80-29fd-11e9-8ffa-b5f9d4f43456.png)

**Comment by uditbh** [comment]
already listed
