### ISSUE TITLE
Whiteboard & Document share: Shapes displayed with different stroke size if teacher draw on a maximized window.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#933]
Using Whiteboard or Document sharing, if teacher draw some shape using the highest stroke size on a maximized window & student window size is smaller comparatively (1024x768).
After draw, the shape displayed with different stroke size on teacher and student window:

**Teacher's window:**
![screenshot from 2019-02-06 11-11-09](https://user-images.githubusercontent.com/36185596/52322663-f11b2c80-29ff-11e9-9a6f-690c7d1b225d.png)

**Student's window:**
![screenshot from 2019-02-06 11-11-15](https://user-images.githubusercontent.com/36185596/52322683-0a23dd80-2a00-11e9-801f-bfc5d049a1f8.png)

**Comment by Sudhanshu0044** [comment]
Not reproduced
