### ISSUE TITLE
If webcam connected between the class, it becomes on after refresh.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#934]
If teacher join the class with no webcam connected & between the class if webcam connected. After refresh the page it become on and enabled:
![screenshot from 2019-02-06 12-38-56](https://user-images.githubusercontent.com/36185596/52325748-33e30180-2a0c-11e9-81f8-3526032ed8c5.png)

It shouldn't be enabled by default after refresh.

**Comment by Shubhamvaishala** [comment]
Not reproduce
