### ISSUE TITLE
Raise Hand: If student raised hand and delete the browser history & close the window, the raised hand still displayed at teacher's window.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#935]
If student raise hand & first he deletes the browser history & then closed the window. The raised hand still displayed at teacher's window:

**When student present:**
![screenshot from 2019-02-07 10-09-47](https://user-images.githubusercontent.com/36185596/52392066-4ae62a00-2ac6-11e9-986c-94d0f247aa33.png)

**When student disconnected:**
![screenshot from 2019-02-07 10-51-02](https://user-images.githubusercontent.com/36185596/52392071-4c175700-2ac6-11e9-8081-93e2ba20c0b1.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
This bug does not exist any more.
