### ISSUE TITLE
Precheck: If teacher runs his own precheck and directly closed the precheck window, student side teacher's blank video appears.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#936]
When teacher click on precheck button & directly close the precheck window & teacher's camera is off.

Student side teacher's video appears as blank:
![screenshot from 2019-02-08 12-35-38](https://user-images.githubusercontent.com/36185596/52463814-72102a80-2b9e-11e9-916b-b2a125660575.png)

**Comment by Shubhamvaishala** [comment]
Not reproduce
