### ISSUE TITLE
Congrea demo: During end session, if teacher select yes to save the session, a dot (.) appears on the screen.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#937]
Using the Congrea demo, if teacher ends the session & select yes to save the session, a **dot(.)** appears on the screen like below:
![screenshot from 2019-02-08 12-47-40](https://user-images.githubusercontent.com/36185596/52464210-04fd9480-2ba0-11e9-8042-1afc848d6658.png)

After a few moments, dialogue box appears to **Download file**:
![screenshot from 2019-02-08 12-47-51](https://user-images.githubusercontent.com/36185596/52464234-1646a100-2ba0-11e9-8c5f-8a1270065c05.png)

**Comment by Shubhamvaishala** [comment]
session end process had change now so this bug is not exist now.
