### ISSUE TITLE
Dashboard apps: Header position differs at document, video or presentation shared / not shared.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#939]
**Document dashboard, Video dashboard & Presentation dashboard heading position should be stable:**

When no document selected:
![screenshot from 2019-02-20 10-36-36](https://user-images.githubusercontent.com/36185596/53067715-72dc8100-34fb-11e9-9285-9724efa0edaf.png)

When some document selected & shared:
![screenshot from 2019-02-20 10-37-22](https://user-images.githubusercontent.com/36185596/53067739-90a9e600-34fb-11e9-8d49-379f0f7e8834.png)

When no video shared:
![screenshot from 2019-02-20 10-38-56](https://user-images.githubusercontent.com/36185596/53067769-c058ee00-34fb-11e9-9296-cc904d6d8da4.png)

When a video shared:
![screenshot from 2019-02-20 10-39-20](https://user-images.githubusercontent.com/36185596/53067783-cf3fa080-34fb-11e9-967c-3c04b424b8e0.png)

When no presentation shared:
![screenshot from 2019-02-20 10-40-16](https://user-images.githubusercontent.com/36185596/53067814-ef6f5f80-34fb-11e9-97ad-b6ae662ec6c9.png)

When a presentation shared:
![screenshot from 2019-02-20 10-40-45](https://user-images.githubusercontent.com/36185596/53067828-ff873f00-34fb-11e9-9b84-72cab7c84342.png)

**Comment by uditbh** [comment]
Closed
