### ISSUE TITLE
Allover enhancements.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#940]
**1. All virtual class user's name, first letter should be capitalized for all apps (private chat, poll, quiz etc):** 

- **Private chat:**

![screenshot from 2019-02-20 10-47-39](https://user-images.githubusercontent.com/36185596/53068197-9d2f3e00-34fd-11e9-89c2-fb3dd36f7574.png)

- **Quiz:**

![screenshot from 2019-02-20 10-58-39](https://user-images.githubusercontent.com/36185596/53068443-83422b00-34fe-11e9-89ac-d6344f84ea84.png)

- **Poll:**

![screenshot from 2019-02-20 10-59-47](https://user-images.githubusercontent.com/36185596/53068477-a8369e00-34fe-11e9-9e4e-9d21084d6199.png)

- **Currently it's for user list & common chat only:**

![screenshot from 2019-02-20 10-47-22](https://user-images.githubusercontent.com/36185596/53068109-2f831200-34fd-11e9-9ee0-ffd23924cf5b.png)

**2. All tooltips must not be clickable.**

**3. All popups should be displayed in the center.**

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
