### ISSUE TITLE
Poll: Back & Publish buttons position interchanged.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#941]
When teacher click on publish poll & the dialogue box appeared, there **Back** & **Publish** buttons position are interchanged:

![screenshot from 2019-02-20 11-01-18](https://user-images.githubusercontent.com/36185596/53068600-124f4300-34ff-11e9-9e34-5f52bb4ad67a.png)

When click on **Publish** button, it looks like below:
![screenshot from 2019-02-20 11-03-29](https://user-images.githubusercontent.com/36185596/53068657-3b6fd380-34ff-11e9-9f60-52bd7dccccb7.png)

The **Publish** button should be display right in both window & their UI should be similar.

**Comment by uditbh** [comment]
Closed
