### ISSUE TITLE
Poll: Creating a new poll, it accepts blank space or dot.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#942]
During create a new poll, if teacher leave only blank space or put any special character and doesn't write anything, it's accepted & published:

**Leaving blank space:**
![screenshot from 2019-02-20 11-10-47](https://user-images.githubusercontent.com/36185596/53068940-365f5400-3500-11e9-8e9f-e58df250ef43.png)

**Putting special characters:**
![screenshot from 2019-02-20 11-10-39](https://user-images.githubusercontent.com/36185596/53068955-45de9d00-3500-11e9-9d30-75f8e5baa4a7.png)

![screenshot from 2019-02-20 11-10-30](https://user-images.githubusercontent.com/36185596/53068959-49722400-3500-11e9-96a9-87be45a97dca.png)

**Comment by Sudhanshu0044** [comment]
Not reproduced
