### ISSUE TITLE
Screen share: During screen share, if screen share selected again, the blank screen appeared & error occurred in console.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#943]
During the screen share, if teacher click on screen share again & cancel. A blank window appears & the following error occurs in console:

**Console error:**
![screenshot from 2019-02-21 14-15-51](https://user-images.githubusercontent.com/36185596/53155835-e954ae00-35e3-11e9-8f1b-b511e07d235c.png)

**The blank window:**
![screenshot from 2019-02-21 14-20-43](https://user-images.githubusercontent.com/36185596/53155833-e659bd80-35e3-11e9-87c2-7d7d93f8eb8e.png)

**Comment by Shubhamvaishala** [comment]
Fix
