### ISSUE TITLE
After changing orientation the data on white board is not appearing properly

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#945]
Steps to reproduce:

1. Draw a line on whiteboard
2. Refresh the page multiple times
3. Change the orientation of the content

Here you will find some of the content appearing on teacher screen is not similar with student screen 
![screenshot from 2019-02-22 17-43-52](https://user-images.githubusercontent.com/38027574/53243722-cce17000-36ce-11e9-88b6-e400e5b1857b.png)

**Comment by meevm** [comment]
Did not reproduce
