### ISSUE TITLE
Navigation issue, selected annotation issue, scribbling on white board issue

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#946]
**Navigation issue:**
After refreshing the browser the page navigation order shows wrong page number

**Selected annotation:**
Create multiple pages on whiteboard, select annotation on every page and refresh the browser, the selected annotation will get unselected after page loads

**Scribble on whiteboard:**
After scribble on whiteboard using freehand different contents reflect on teacher white board and different content reflects on student screen

![screenshot from 2019-02-22 18-01-36](https://user-images.githubusercontent.com/38027574/53243905-53964d00-36cf-11e9-9b9d-c9ea87d16283.png)

**Comment by meevm** [comment]
Did not reproduce
