### ISSUE TITLE
Student refresh issue

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#947]
When student refresh the browser and doesn't clicks on "continue" then also student is appeared on the user list of the teacher
In this case if teacher requests for screen share to that particular student the congrea page of the student gets disable and no clicks on that page works.
![screenshot from 2019-02-22 18-38-17](https://user-images.githubusercontent.com/38027574/53244654-89d4cc00-36d1-11e9-9893-80efcf45d407.png)

**Comment by Shubhamvaishala** [comment]
reproduced in same steps

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
