### ISSUE TITLE
Recording play on mobile: During the recording loading from server, the dialogue box not appeared properly.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#948]
When play a recording on Mobile phone & the recording is being downloaded from server. The dialogue box appeared is not visible completely. 

![456448846907228994](https://user-images.githubusercontent.com/36185596/53472917-092a1d00-3a8f-11e9-8452-f1232f693407.png)

**Comment by uditbh** [comment]
Deprecated
