### ISSUE TITLE
Whiteboard: After new user join, teacher visits directly on some random page using bottom navigation bar & click to next or previous, students get the different page data.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#949]
When teacher draw some pages on whiteboard & directly visits to a random page using the bottom navigation bar. After that either teacher goes to next or previous page, the student gets the another page data. 

This error reproducing randomly.

**Comment by Sudhanshu0044** [comment]
Not being reproduced because the navigation has been removed from the Congrea
