### ISSUE TITLE
Screen share: After request screen share, if teacher refresh his screen, some console error occurs.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#951]
Teacher requests screen share with student & after screen shared, teacher refresh his screen. The following error occured in console:

![screenshot from 2019-03-05 12-29-07](https://user-images.githubusercontent.com/36185596/53787534-34a48000-3f45-11e9-85e8-6d1fbda48c73.png)

**Comment by Shubhamvaishala** [comment]
Not reproduce again
