### ISSUE TITLE
Poll: The poll creator name displays the teacher's username instead of Teacher's name.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#952]
When teacher creates the poll, the creator field displays the teacher's moodle username instead of Teacher's name.

![screenshot from 2019-03-05 15-41-27](https://user-images.githubusercontent.com/36185596/53797914-2cf0d580-3f5d-11e9-90e2-67880f8643c7.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
