### ISSUE TITLE
Whiteboard & Document sharing: Pagination font size mismatch for student window.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#956]
At student side, the whiteboard & document sharing pagination font size mismatch:

![screenshot from 2019-03-08 17-16-42](https://user-images.githubusercontent.com/36185596/54027017-fb2e7780-41c5-11e9-98f9-cda981b042ac.png)

**Comment by uditbh** [comment]
Closed

**Comment by uditbh** [comment]
Closed
