### ISSUE TITLE
Precheck: If webcam neither allowed, nor blocked during the precheck, the precheck window UI misplaced.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#958]
During precheck, if camera neither allowed nor blocked, the precheck window appears like this (UI disturbed):

![Screenshot from 2019-03-11 15-23-08](https://user-images.githubusercontent.com/36185596/54115840-6c169f00-4413-11e9-9eb4-76ea64e0386d.png)

**Comment by uditbh** [comment]
the problem is we are not getting "nowebcam" class in virtualclassCont till the user not allowing or blocking his camera. This issue will fix later by Suman Sir.

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
