### ISSUE TITLE
Video & Presentation share: If save with blank URL, the invalid URL display should be improved.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#960]
If teacher is present on Video or Presentation share & click the save button without any URL, a warning box appears with a message **"Invalid URL"**. It's display style should be improved.

![Screenshot from 2019-03-11 17-15-54](https://user-images.githubusercontent.com/36185596/54121946-b99a0880-4421-11e9-80c8-0eb772bccd20.png)

**Comment by uditbh** [comment]
close
