### ISSUE TITLE
Whiteboard: The hover shadow not displaying for shapes icon.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#961]
When hover on shapes icon, the shadow not displaying like other icons:

![Screenshot from 2019-03-11 17-29-28](https://user-images.githubusercontent.com/36185596/54122693-bdc72580-4423-11e9-898d-d83fac0e1c3e.png)

![Screenshot from 2019-03-11 17-29-31](https://user-images.githubusercontent.com/36185596/54122691-bdc72580-4423-11e9-9d47-de712d08cdef.png)

**Comment by uditbh** [comment]
Closed
