### ISSUE TITLE
Precheck: No Microphone message should be displayed.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#962]
During precheck, if microphone not connected. The same message displayed (when microphone connected):
![Screenshot from 2019-03-15 12-17-01](https://user-images.githubusercontent.com/36185596/54413669-89ea4980-471c-11e9-8e17-3a4f4e831059.png)

It should display a message like webcam window:
**"Microphone is not available, or not connected properly."**

**Comment by Sudhanshu0044** [comment]
Not reproduced

**Comment by ypshukla** [comment]
It's an improvement. The above stated message should be displayed in case of unavailability of Microphone.

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
