### ISSUE TITLE
Precheck: When join the class on laptop (resolution: 1366 x 768), the webcam window UI affected.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#966]
**When user join the virtual class with Laptop (Resolution: 1366 x 768), during the precheck, the webcam window UI affected.**

![Untitled 1](https://user-images.githubusercontent.com/36185596/55144123-26bdd580-5166-11e9-8502-5e1d66bed403.png)

**When run the precheck during the class:**
![Untitled 2](https://user-images.githubusercontent.com/36185596/55144151-2f161080-5166-11e9-9959-b592fced3c40.png)

**Comment by uditbh** [comment]
Fixed
