### ISSUE TITLE
Student window refreshed & teacher ended the session, the student window became unresponsive.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#967]
If student refreshed his window & didn't clicked the **Continue** button. At the same time if teacher ended the session, the student window became unresponsive.

![Screenshot from 2019-03-28 15-21-36](https://user-images.githubusercontent.com/36185596/55148085-94b9cb00-516d-11e9-8911-7a5192c025e0.png)

**Comment by Shubhamvaishala** [comment]
Fix
