### ISSUE TITLE
Audio & Video enabled by Moodle (Congrea activity settings), but after join the class all video disabled.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#968]
Teacher has set the Audio & Video both enabled from Congrea activity settings. But after join the class all video disabled by default. The all video disabled also after session end.

**Congrea Activity settings:**
![Screenshot from 2019-03-28 15-35-57](https://user-images.githubusercontent.com/36185596/55148935-37267e00-516f-11e9-88f6-feab10a1c5fc.png)

**Virtual class settings after join:**
![Screenshot from 2019-03-28 15-36-04](https://user-images.githubusercontent.com/36185596/55148941-3988d800-516f-11e9-8327-61503e5b5684.png)

**Comment by Shubhamvaishala** [comment]
Not reproduce
