### ISSUE TITLE
Private chat: When user video disabled, the user icon is clickable & private chat opened. But after enabling the user video, the user icon clickable but nothing happens after click.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#969]
**If user's video disabled & user icon displayed the first letter of their name. In such case the user icon is clickable and private chat opened after click:**

![screenshot-demo congrea net-2019 03 29-11-38-20](https://user-images.githubusercontent.com/36185596/55212940-aeafe800-5217-11e9-8690-62a0b5908779.png)

**When user video enabled, the user icon is clickable but nothing happens after click:**

![screenshot-demo congrea net-2019 03 29-11-38-20 (2)](https://user-images.githubusercontent.com/36185596/55213033-149c6f80-5218-11e9-9a88-fe5e43a24f8b.png)

**Comment by Shubhamvaishala** [comment]
Fix
