### ISSUE TITLE
Common chat: When student get the notification for common chat, the tooltip misplaced.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#970]
When teacher send some message in common chat and the notification highlights at student side. The tooltip for common chat misplaced at student side:

![Screenshot from 2019-03-29 13-59-56](https://user-images.githubusercontent.com/36185596/55219460-f724d100-522a-11e9-98a8-af8be3fbc86a.png)

**Comment by uditbh** [comment]
fixed
