### ISSUE TITLE
Problem in video playing on Firefox browser

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#972]
Upload video file on Firefox and trying to playing it shows error "**No compatible source was found for this media**'
Same video uploaded on chrome run without any issue.
Attached error message
![Screenshot from 2019-04-02 17-23-26](https://user-images.githubusercontent.com/38027574/55400661-19408b00-556c-11e9-8c69-eaa077059a05.png)

**Comment by meevm** [comment]
Did not reproduce
