### ISSUE TITLE
After session end teacher's video disabled but still displayed the paused video to student.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#973]
If teacher's video enabled and teacher ends the session. After session end teacher's video disabled automatically but the student side teacher's video still displayed in paused format.

**Teacher's window after session end:**
![Screenshot from 2019-04-05 11-59-09](https://user-images.githubusercontent.com/36185596/55607730-8d607600-579a-11e9-8e1e-f0ed0a22cf4a.png)

**Student's window after session end:**
![Screenshot from 2019-04-05 11-59-11](https://user-images.githubusercontent.com/36185596/55607733-90f3fd00-579a-11e9-9500-e86691642b47.png)

**Comment by Shubhamvaishala** [comment]
Fix
