### ISSUE TITLE
Whiteboard: If draw some text on smaller window(1024x768) & maximize the window, the stroke size differs from previous drawn object.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#976]
If the current window size is 1024x768 & teacher draw some object. After draw if maximize the window, the previous drawn object displayes some darker. After maximize, stroke size differs from previous.

**Comment by Shubhamvaishala** [comment]
we can't find any color difference. after using this scenario.

**Comment by ypshukla** [comment]
Please refer to this screenshot (The both rectangle drawn on stroke size 3):

![Screenshot from 2019-04-30 10-29-54](https://user-images.githubusercontent.com/36185596/56941578-f1c0ec00-6b32-11e9-93b9-e109c29d5ac6.png)

**Comment by Shubhamvaishala** [comment]
same bug already available in github bug list..#933
