### ISSUE TITLE
Text colour and size changing on whiteboard

### ISSUE THREAD

**Issue by Sudhanshu0044** [congrea/virtualclass#977]
Steps to reproduce:

1. Write a sentence1 on whiteboard with red colour and text size 30px
2. Write sentence2 text in blue colour text size 25px
3. Now edit the sentence1 the colour will get change to blue and text size will be 25px.
![Screenshot from 2019-04-22 14-04-22](https://user-images.githubusercontent.com/38027574/56491892-a93c7980-6507-11e9-87da-4bc839d1b2b6.png)
![Screenshot from 2019-04-22 14-04-33](https://user-images.githubusercontent.com/38027574/56491893-a93c7980-6507-11e9-909f-a8537267c7f1.png)

**Comment by jgupta** [comment]
It is expected. Latest settings apply when we edit text. If we somehow retain existing settings then how will use change size or colour?
