### ISSUE TITLE
During video sharing, if teacher requests screen share with student & student cancel it. The student screen becomes blank.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#983]
During video sharing, if teacher requests screen share with student:

-  Who doesn't have Desktop selector & select yes. The below message appears:
![Screenshot from 2019-04-25 12-36-11](https://user-images.githubusercontent.com/36185596/56716101-198d0a00-6757-11e9-98b6-89f1b517728a.png)

If cancel this message, the screen becomes blank:
![Screenshot from 2019-04-25 12-36-14](https://user-images.githubusercontent.com/36185596/56716124-2b6ead00-6757-11e9-80da-aa39dd14725b.png)

- Who have installed Desktop selector in the browser & select yes. The below message appears:
![Screenshot from 2019-04-25 12-37-37](https://user-images.githubusercontent.com/36185596/56716214-5ce77880-6757-11e9-9c71-e25ab5faee70.png)

If cancel this message, the screen becomes blank:
![Screenshot from 2019-04-25 12-37-40](https://user-images.githubusercontent.com/36185596/56716259-7b4d7400-6757-11e9-97a7-c9e0b6d8d4cd.png)

**For both above situation, if student cancel the request, he must be redirected to the video.**

**Comment by nirmala10** [comment]
fixed.
