### ISSUE TITLE
Private chat: Teacher name displayed with three dots.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#985]
When teacher texts to student in private chat & student refresh his window. The teacher's name displayed with three dots:

![Screenshot from 2019-04-25 14-10-41](https://user-images.githubusercontent.com/36185596/56722174-1e0bef80-6764-11e9-9511-0d50e57277cf.png)

**Comment by uditbh** [comment]
Closed

**Comment by ypshukla** [comment]
Still appearing after refresh.

**Comment by Sudhanshu0044** [comment]
Not reproduced
