### ISSUE TITLE
On whiteboard lengthy text was not displayed properly

### ISSUE THREAD

**Issue by Sachi01** [congrea/virtualclass#991]
WhiteBoard:

While writing a lengthy text the complete text was not displayed even after using fit to screen.Neither option to scroll and read text was available.

Kindly find attached screenshot for reference.
![Screen Shot 2019-05-02 at 10 52 13 AM](https://user-images.githubusercontent.com/50192706/57058613-8744b300-6cce-11e9-8b03-ce770ad0b353.png)

![Screen Shot 2019-05-02 at 10 51 08 AM](https://user-images.githubusercontent.com/50192706/57058633-9c214680-6cce-11e9-999b-1c1a77c43518.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
![wb text](https://user-images.githubusercontent.com/38027574/62916951-0d859080-bdb8-11e9-9a8f-4d9ad7f80ea0.PNG)

**Comment by suman** [comment]
Whiteboard bugs are fixed by integrating new version of fabric.js.
